### ISSUE TITLE
包已经pip install，但是运行报缺失。

### ISSUE THREAD

**Issue by ImJoyed** [THUDM/GLM-4#108]
我按composite_demo里的readme，在conda环境中安装了requirements.txt要求的包，但是运行依然提示缺少包。
使用pip show也能看到该包已安装，python解释器中import也没问题。
注释掉cogview相关的引用后，又提示doc包缺失，是我的环境有啥问题吗。
```py
2024-06-07 15:03:39.618 Uncaught app exception
Traceback (most recent call last):
  File "/home/model/.local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 534, in _run_script
    exec(code, module.__dict__)
  File "/data/Project/GLM-4/composite_demo/src/main.py", line 19, in <module>
    from client import Client, ClientType, get_client
  File "/data/Project/GLM-4/composite_demo/src/client.py", line 18, in <module>
    from tools.tool_registry import ALL_TOOLS
  File "/data/Project/GLM-4/composite_demo/src/tools/tool_registry.py", line 20, in <module>
    from .cogview import tool_call as cogview
  File "/data/Project/GLM-4/composite_demo/src/tools/cogview.py", line 2, in <module>
    from zhipuai import ZhipuAI
ModuleNotFoundError: No module named 'zhipuai'
^C  Stopping...
(glm-4-demo) model@ChatGLM--Q35-ICH9-2009:/data/Project/GLM-4/composite_demo$ pip show zhipuai
Name: zhipuai
Version: 2.1.0.20240521
Summary: A SDK library for accessing big model apis from ZhipuAI
Home-page:
Author: Zhipu AI
Author-email:
License:
Location: /opt/anaconda3/envs/glm-4-demo/lib/python3.12/site-packages
Requires: cachetools, httpx, pydantic, pyjwt
Required-by:
```

**Comment by ImJoyed** [comment]
已找到问题，系环境变量~/.local/bin中有一个streamlit，而conda环境中的streamlit路径靠后，默认使用了一个错误版本的streamlit导致
