### ISSUE TITLE
[BUG] OOM:torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 108.00 MiB. GPU，加载多模态选项后，后台nvidia-smi会持续增长到32G后，报错

### ISSUE THREAD

**Issue by aben1900** [THUDM/GLM-4#147]
### System Info / 系統信息

![image](https://github.com/THUDM/GLM-4/assets/10842373/aa7e47d8-79b5-4edd-b70f-e6edfa3d26f0)
cuda12.1
python 3.12
模型 glm-4v-9b，显存不释放吗，还是32G不够。如下图的配置，出错信息如下

### Information / 问题信息

- [x] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

1. 加载glm-4 composite-demo，运行localhost:3000，运行localhost:8501，成功，
2. all tools选项的内容正常运行，
3. 加载多模态时，会出现累积的显存，然后到上限后报错。错误如下：
2024-06-12 15:14:34.284 Uncaught app exception
Traceback (most recent call last):
  File "/sdb/chatgpt/GLM-4/composite_demo/glm4_pip/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 575, in _run_script
    self._session_state.on_script_will_rerun(
  File "/sdb/chatgpt/GLM-4/composite_demo/glm4_pip/lib/python3.12/site-packages/streamlit/runtime/state/safe_session_state.py", line 65, in on_script_will_rerun
    self._state.on_script_will_rerun(latest_widget_states)
  File "/sdb/chatgpt/GLM-4/composite_demo/glm4_pip/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 517, in on_script_will_rerun
    self._call_callbacks()
  File "/sdb/chatgpt/GLM-4/composite_demo/glm4_pip/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 530, in _call_callbacks
    self._new_widget_state.call_callback(wid)
  File "/sdb/chatgpt/GLM-4/composite_demo/glm4_pip/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 274, in call_callback
    callback(*args, **kwargs)
  File "/sdb/chatgpt/GLM-4/composite_demo/src/main.py", line 126, in page_changed
    st.session_state.client = build_client(Mode(new_page))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/sdb/chatgpt/GLM-4/composite_demo/src/main.py", line 116, in build_client
    return get_client(VLM_MODEL_PATH, ClientType.HF)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/sdb/chatgpt/GLM-4/composite_demo/glm4_pip/lib/python3.12/site-packages/streamlit/runtime/caching/cache_utils.py", line 165, in wrapper
    return cached_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/sdb/chatgpt/GLM-4/composite_demo/glm4_pip/lib/python3.12/site-packages/streamlit/runtime/caching/cache_utils.py", line 194, in __call__
    return self._get_or_create_cached_value(args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/sdb/chatgpt/GLM-4/composite_demo/glm4_pip/lib/python3.12/site-packages/streamlit/runtime/caching/cache_utils.py", line 221, in _get_or_create_cached_value
    return self._handle_cache_miss(cache, value_key, func_args, func_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/sdb/chatgpt/GLM-4/composite_demo/glm4_pip/lib/python3.12/site-packages/streamlit/runtime/caching/cache_utils.py", line 277, in _handle_cache_miss
    computed_value = self._info.func(*func_args, **func_kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/sdb/chatgpt/GLM-4/composite_demo/src/client.py", line 92, in get_client
    return HFClient(model_path)
           ^^^^^^^^^^^^^^^^^^^^
  File "/sdb/chatgpt/GLM-4/composite_demo/src/clients/hf.py", line 37, in __init__
    self.model.to("cuda")
  File "/sdb/chatgpt/GLM-4/composite_demo/glm4_pip/lib/python3.12/site-packages/transformers/modeling_utils.py", line 2692, in to
    return super().to(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/sdb/chatgpt/GLM-4/composite_demo/glm4_pip/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1173, in to
    return self._apply(convert)
           ^^^^^^^^^^^^^^^^^^^^
  File "/sdb/chatgpt/GLM-4/composite_demo/glm4_pip/lib/python3.12/site-packages/torch/nn/modules/module.py", line 779, in _apply
    module._apply(fn)
  File "/sdb/chatgpt/GLM-4/composite_demo/glm4_pip/lib/python3.12/site-packages/torch/nn/modules/module.py", line 779, in _apply
    module._apply(fn)
  File "/sdb/chatgpt/GLM-4/composite_demo/glm4_pip/lib/python3.12/site-packages/torch/nn/modules/module.py", line 779, in _apply
    module._apply(fn)
  [Previous line repeated 3 more times]
  File "/sdb/chatgpt/GLM-4/composite_demo/glm4_pip/lib/python3.12/site-packages/torch/nn/modules/module.py", line 804, in _apply
    param_applied = fn(param)
                    ^^^^^^^^^
  File "/sdb/chatgpt/GLM-4/composite_demo/glm4_pip/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1159, in convert
    return t.to(
           ^^^^^
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 108.00 MiB. GPU

nvidia-smi的结果如下：
![image](https://github.com/THUDM/GLM-4/assets/10842373/33cc81a3-221d-4f2c-97fa-a187598127c0)

### Expected behavior / 期待表现

需要能解决问题。

**Comment by zRzRzRzRzRzRzR** [comment]
composite demo用不了glm-4v的vLLM，只能用hf client，使用显存28G，你是hf client到32G吗

**Comment by aben1900** [comment]
> composite demo用不了glm-4v的vLLM，只能用hf client，使用显存28G，你的对话长度到多少了

1）在composite demo没有用vllm
2）all tools加载模型后，nvidia-smi使用了
![image](https://github.com/THUDM/GLM-4/assets/10842373/2ab038d1-680b-44e2-8541-9baf7f92b279)
而且一直没有释放显存，然后再切换到多模态，就会持续上升到32G后OOM
3）如果启动项目后，直接进入“多模态”，是可以进行相关的识图的，但如果是切换模型，就会OOM
结论：加载模型后，切换后，一直没有释放，可能是这个原因

**Comment by zRzRzRzRzRzRzR** [comment]
收到，我们会检查一下

**Comment by zRzRzRzRzRzRzR** [comment]
这个问题刚才复现了，这两天会修

**Comment by zRzRzRzRzRzRzR** [comment]
已经修复

**Comment by zhongfuxiao** [comment]
> composite demo用不了glm-4v的vLLM，只能用hf client，使用显存28G，你的对话长度到多少了

@zRzRzRzRzRzRzR 大佬好，想咨询几个问题。
1.使用composite demo文档解读，显存用量是如何换算的？我使用glm-4-9b-chat，load int4，占用不到8G，传入265kb大小的txt文档，提问后和输出回答时显存在29g。后面换到了glm-4-9b-chat-1m，同样的本文和问题，同样int4，起始占用不到8G，提问后达到44G，输出答案时占用33G。想问下两个模型和文档大小占用显存的换算关系
2.后续在使用1m模型时，文档换成了一个1.2mb大小的txt文档，L20 48G单卡发现不够用。设备上4卡，02长期稳定占用。所以我设置了cuda_visible_devices=1,3，hf客户端中device_map=auto，发现还是提示内存不足，且3没有占用。是我的用法不对吗？
望大佬抽空解答
