### ISSUE TITLE
使用GLM-4-chat，在composite-demo，All Tools对话 报错 raise Empty _queue.Empty

### ISSUE THREAD

**Issue by Mizoreeeee** [THUDM/GLM-4#151]
### System Info / 系統信息

torch: 2.3.1+cu121
Python: 3.10.14
Transformers: 4.40.0
OS: Windows 11 23H2

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

```PowerShell
conda activate GLM-4-chat
pip install -r requirements.txt
cd broswer
pnpm install
```

`browser/src/config.ts`和`src/tools/config.py`的API都填了

```PowerShell
pnpm start
streamlit run src/main.py
```

1. 选择All Tools
2. 输入你好

浏览器返回的错误信息
```
Uncaught exception: Traceback (most recent call last): File "D:\python temp\GLM-4-chat\composite_demo\src\main.py", line 287, in main for response, chat_history in client.generate_stream( File "D:\python temp\GLM-4-chat\composite_demo\src\clients\hf.py", line 57, in generate_stream for token_text in streamer: File "C:\Users\89555\anaconda3\envs\GLM-4-chat\lib\site-packages\transformers\generation\streamers.py", line 223, in next value = self.text_queue.get(timeout=self.timeout) File "C:\Users\89555\anaconda3\envs\GLM-4-chat\lib\queue.py", line 179, in get raise Empty _queue.Empty
```

PowerShell报错
```
C:\Users\89555\anaconda3\envs\GLM-4-chat\lib\site-packages\huggingface_hub\file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
C:\Users\89555\.cache\huggingface\modules\transformers_modules\THUDM\glm-4-9b-chat\6f060dcb542d48b6bc743628634924b271545428\modeling_chatglm.py:189: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at ..\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:455.)
  context_layer = torch.nn.functional.scaled_dot_product_attention(query_layer, key_layer, value_layer,
Traceback (most recent call last):
  File "D:\python temp\GLM-4-chat\composite_demo\src\main.py", line 287, in main
    for response, chat_history in client.generate_stream(
  File "D:\python temp\GLM-4-chat\composite_demo\src\clients\hf.py", line 57, in generate_stream
    for token_text in streamer:
  File "C:\Users\89555\anaconda3\envs\GLM-4-chat\lib\site-packages\transformers\generation\streamers.py", line 223, in __next__
    value = self.text_queue.get(timeout=self.timeout)
  File "C:\Users\89555\anaconda3\envs\GLM-4-chat\lib\queue.py", line 179, in get
    raise Empty
_queue.Empty
Traceback (most recent call last):
  File "D:\python temp\GLM-4-chat\composite_demo\src\main.py", line 287, in main
    for response, chat_history in client.generate_stream(
  File "D:\python temp\GLM-4-chat\composite_demo\src\clients\hf.py", line 57, in generate_stream
    for token_text in streamer:
  File "C:\Users\89555\anaconda3\envs\GLM-4-chat\lib\site-packages\transformers\generation\streamers.py", line 223, in __next__
    value = self.text_queue.get(timeout=self.timeout)
  File "C:\Users\89555\anaconda3\envs\GLM-4-chat\lib\queue.py", line 179, in get
    raise Empty
_queue.Empty
```

直接在python里用pytorch没问题

### Expected behavior / 期待表现

正常对话

**Comment by Dzy0815** [comment]
可能是超时时间设置的太短了，在/src/clients/hf.py 里面把44行的timeout时间改久一点应该就可以了。我也有这个错，把时间改了就好了。

**Comment by Mizoreeeee** [comment]
> 可能是超时时间设置的太短了，在/src/clients/hf.py 里面把44行的timeout时间改久一点应该就可以了。我也有这个错，把时间改了就好了。

确实，谢谢

**Comment by mashibin** [comment]
> > 可能是超时时间设置的太短了，在/src/clients/hf.py 里面把44行的timeout时间改久一点应该就可以了。我也有这个错，把时间改了就好了。
> 
> 确实，谢谢

改成多少合适呢
