### ISSUE TITLE
Glm-4v-9b有提供多轮对话的代码demo吗？

### ISSUE THREAD

**Issue by jhrsya** [THUDM/GLM-4#156]
例如qwen-vl可以直接使用model.chat（）进行多轮对话。

还是得自己写代码改呢？

**Comment by zRzRzRzRzRzRzR** [comment]
cli_vision_demo就是多轮对话的

**Comment by jhrsya** [comment]
> cli_vision_demo就是多轮对话的

我看里面一次完整的对话只能开始输入一张图片。可以通过修改这个代码实现每一轮对话都可以输入一张图片（可输入可不输入）吗？

如果可以的话我尝试改下，还是模型本身就不支持呢？

**Comment by jhrsya** [comment]
> cli_vision_demo就是多轮对话的

当我尝试直接在每一轮对话加入图片时，出现以下bug: 
```
Traceback (most recent call last):
  File "glm4v-9b.py", line 48, in <module>
    inputs = tokenizer.apply_chat_template(history,
  File "/root/.cache/huggingface/modules/transformers_modules/glm-4v-9b/tokenization_chatglm.py", line 236, in apply_chat_template
    result = handle_single_conversation(conversation)
  File "/root/.cache/huggingface/modules/transformers_modules/glm-4v-9b/tokenization_chatglm.py", line 209, in handle_single_conversation
    assert input_image is None, "Multiple images are not supported"
AssertionError: Multiple images are not supported
```
我看这个文件是下载的glm-4v-9b模型中的tokenization_chatglm.py文件，这里的apply_chat_template方法中只实现了handle_single_conversation方法。请问是不是模型本身就不支持每一轮对话都输入一张图片（可输入可不输入）吗？

**Comment by zRzRzRzRzRzRzR** [comment]
只有第一段可以输入图片，后面不能输入图片， 所有的对话要针对第一个输入的图片
