### ISSUE TITLE
复现glm-4v-9b出现RuntimeError:shape错误

### ISSUE THREAD

**Issue by kkczw** [THUDM/GLM-4#182]
### System Info / 系統信息

cuda版本：11.3
python版本：3.10
torch:1.12.1
操作系统：windows server 2019

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

1、相同的环境，可复现glm-4-9b-chat,复现glm-4v-9b出现下面的问题：
Traceback (most recent call last):
  File "D:\jiangqr\.conda\envs\zhipu4-chat\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "D:\jiangqr\.conda\envs\zhipu4-chat\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "D:\jiangqr\.conda\envs\zhipu4-chat\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "D:\jiangqr\.conda\envs\zhipu4-chat\lib\site-packages\transformers\generation\utils.py", line 1622, in generate
    result = self._sample(
  File "D:\jiangqr\.conda\envs\zhipu4-chat\lib\site-packages\transformers\generation\utils.py", line 2791, in _sample
    outputs = self(
  File "D:\jiangqr\.conda\envs\zhipu4-chat\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\.cache\huggingface\modules\transformers_modules\glm-4v-9b\modeling_chatglm.py", line 1012, in forward
    transformer_outputs = self.transformer(
  File "D:\jiangqr\.conda\envs\zhipu4-chat\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\.cache\huggingface\modules\transformers_modules\glm-4v-9b\modeling_chatglm.py", line 901, in forward
    hidden_states, presents, all_hidden_states, all_self_attentions = self.encoder(
  File "D:\jiangqr\.conda\envs\zhipu4-chat\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\.cache\huggingface\modules\transformers_modules\glm-4v-9b\modeling_chatglm.py", line 658, in forward
    layer_ret = layer(
  File "D:\jiangqr\.conda\envs\zhipu4-chat\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\.cache\huggingface\modules\transformers_modules\glm-4v-9b\modeling_chatglm.py", line 561, in forward
    attention_output, kv_cache = self.self_attention(
  File "D:\jiangqr\.conda\envs\zhipu4-chat\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\.cache\huggingface\modules\transformers_modules\glm-4v-9b\modeling_chatglm.py", line 458, in forward
    context_layer = self.core_attention(query_layer, key_layer, value_layer, attention_mask)
  File "D:\jiangqr\.conda\envs\zhipu4-chat\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\.cache\huggingface\modules\transformers_modules\glm-4v-9b\modeling_chatglm.py", line 310, in forward
    value_layer = value_layer.view(output_size[0] * output_size[1], value_layer.size(2), -1)
RuntimeError: shape '[51552, 1611, -1]' is invalid for input of size 6598656
Traceback (most recent call last):
  File "C:\Users\Desktop\glm4\GLM-4-main\basic_demo\trans_cli_vision_demo.py", line 120, in <module>
    for new_token in streamer:
  File "D:\jiangqr\.conda\envs\zhipu4-chat\lib\site-packages\transformers\generation\streamers.py", line 223, in __next__
    value = self.text_queue.get(timeout=self.timeout)
  File "D:\jiangqr\.conda\envs\zhipu4-chat\lib\queue.py", line 179, in get
    raise Empty
_queue.Empty
2、修改对应文件出错代码后，再次运行，修改的文件恢复到没修改的文件，也就是修改无效

### Expected behavior / 期待表现

希望解决此问题

**Comment by zRzRzRzRzRzRzR** [comment]
多卡了吧，更新一下最新hf的代码

**Comment by kkczw** [comment]
已解决，需要torch>2.x版本以上
