### ISSUE TITLE
无法使用 LlamaIndex 导入

### ISSUE THREAD

**Issue by laozhai507** [THUDM/GLM-4#183]
### System Info / 系統信息

transformers                            4.41.2
torch                                   2.3.1
llama-index-llms-huggingface            0.2.3
llama-index                             0.10.44

### Who can help? / 谁可以帮助到您？

@zRzRzRzRzRzRzR 

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

1. `Settings.llm = AutoModelForCausalLM.from_pretrained('/root/autodl-tmp/glm-4-9b-chat', trust_remote_code=True, device_map='auto')`
2. 
```
Settings.llm = HuggingFaceLLM(
    model_name='/root/autodl-tmp/glm-4-9b-chat',
    tokenizer=AutoTokenizer.from_pretrained('/root/autodl-tmp/glm-4-9b-chat', trust_remote_code=True),
    context_window=3900,
    max_new_tokens=256,
    generate_kwargs={'tmperature':0.7, 'top_k':50, 'top_p':0.95},
#     # transform inputs into Llama2 format
#     messages_to_prompt=messages_to_prompt,
#     completion_to_prompt=completion_to_prompt,
    device_map='cuda',
    model_kwargs={'trust_remote_code':True}
)
```

### Expected behavior / 期待表现

1. 输出
```
Traceback (most recent call last):
  File "mmRAG/src/rag/performance_evaluation.py", line 109, in <module>
    query_engine = index.as_query_engine(
  File "/root/miniconda3/lib/python3.8/site-packages/llama_index/core/indices/base.py", line 407, in as_query_engine
    return RetrieverQueryEngine.from_args(
  File "/root/miniconda3/lib/python3.8/site-packages/llama_index/core/query_engine/retriever_query_engine.py", line 110, in from_args
    response_synthesizer = response_synthesizer or get_response_synthesizer(
  File "/root/miniconda3/lib/python3.8/site-packages/llama_index/core/response_synthesizers/factory.py", line 73, in get_response_synthesizer
    llm.metadata,
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1709, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'ChatGLMForConditionalGeneration' object has no attribute 'metadata'
```
2. 输出
```
Traceback (most recent call last):
  File "mmRAG/src/rag/performance_evaluation.py", line 61, in <module>
    tokenizer=AutoTokenizer.from_pretrained('/root/autodl-tmp/glm-4-9b-chat', trust_remote_code=True),
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/models/auto/tokenization_auto.py", line 865, in from_pretrained
    return tokenizer_class.from_pretrained(
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 2110, in from_pretrained
    return cls._from_pretrained(
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 2336, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/glm-4-9b-chat/tokenization_chatglm.py", line 35, in __init__
    rank = int(rank)
ValueError: invalid literal for int() with base 10: 'https://git-lfs.github.com/spec/v1'
```
非常感谢您的帮助！

**Comment by zRzRzRzRzRzRzR** [comment]
你尝试直接下载模型到本地呢

**Comment by laozhai507** [comment]
> 你尝试直接下载模型到本地呢

您好，我已经提前下载好了，在本地导入出错了 @zRzRzRzRzRzRzR

**Comment by zRzRzRzRzRzRzR** [comment]
我估计是因为glm相对于llamaindex多了一个metadata字段，因为openai格式中是只有content没有metadata的，在套模板的时候估计遇到了这个问题？我也没尝试llamaindex，暂时没办法改

**Comment by laozhai507** [comment]
> 我估计是因为glm相对于llamaindex多了一个metadata字段，因为openai格式中是只有content没有metadata的，在套模板的时候估计遇到了这个问题？我也没尝试llamaindex，暂时没办法改

好的吧，谢谢了 @zRzRzRzRzRzRzR
