### ISSUE TITLE
更新 openai_api_server.py后，post 简单 message 报错，之前是可以正常运行

### ISSUE THREAD

**Issue by HenryLiang** [THUDM/GLM-4#193]
### System Info / 系統信息

python=3.10.14
cuda=12.4
pytorch=2.3
显卡 v100

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

跑一个简单例子或者跑 openai_api_request.py：
messages = [
        {'role': 'user', 'content': '你好'},
    ]

    # print(call_glm([{"role": "user", "content": "你是哪个大模型？"}]))
    client = OpenAI(
        base_url="http://localhost:8000/v1",
        api_key="token-abc123",  # 随便设，只是为了通过接口参数校验
    )

    completion = client.chat.completions.create(
        model="glm-4",
        messages=messages,
        stream=False,
        temperature=0.1,
    )

    print(completion.choices[0].message)

报错信息如下：
INFO:     10.0.88.212:59639 - "POST /v1/chat/completions HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/opt/cloudera/parcels/Anaconda/envs/xinference/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/opt/cloudera/parcels/Anaconda/envs/xinference/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
  File "/opt/cloudera/parcels/Anaconda/envs/xinference/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/opt/cloudera/parcels/Anaconda/envs/xinference/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/cloudera/parcels/Anaconda/envs/xinference/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/opt/cloudera/parcels/Anaconda/envs/xinference/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/opt/cloudera/parcels/Anaconda/envs/xinference/lib/python3.10/site-packages/starlette/middleware/cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "/opt/cloudera/parcels/Anaconda/envs/xinference/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/opt/cloudera/parcels/Anaconda/envs/xinference/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/opt/cloudera/parcels/Anaconda/envs/xinference/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/opt/cloudera/parcels/Anaconda/envs/xinference/lib/python3.10/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/cloudera/parcels/Anaconda/envs/xinference/lib/python3.10/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/opt/cloudera/parcels/Anaconda/envs/xinference/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/opt/cloudera/parcels/Anaconda/envs/xinference/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/opt/cloudera/parcels/Anaconda/envs/xinference/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/opt/cloudera/parcels/Anaconda/envs/xinference/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/opt/cloudera/parcels/Anaconda/envs/xinference/lib/python3.10/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
  File "/opt/cloudera/parcels/Anaconda/envs/xinference/lib/python3.10/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
  File "/opt/cloudera/parcels/Anaconda/envs/xinference/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/data/project/GLM-4/./basic_demo/openai_api_server.py", line 376, in create_chat_completion
    async for response in generate_stream_glm4(gen_params):
  File "/data/project/GLM-4/./basic_demo/openai_api_server.py", line 212, in generate_stream_glm4
    async for output in engine.generate(inputs=inputs, sampling_params=sampling_params, request_id=f"{time.time()}"):
TypeError: AsyncLLMEngine.generate() got an unexpected keyword argument 'inputs'

### Expected behavior / 期待表现

请求正常返回

**Comment by Smile-L-up** [comment]
你好，我也遇到这个问题了，请问是如何解决的呢？
