### ISSUE TITLE
openai_api_server.py stream tool_calls keyError

### ISSUE THREAD

**Issue by hushuitian** [THUDM/GLM-4#194]
### System Info / 系統信息

ubuntu 22.04,cuda 12.1, python 3.10, 2 T4 GPUs

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

[openai_api_request_stream_tool_calls.py.txt](https://github.com/user-attachments/files/15862930/openai_api_request_stream_tool_calls.py.txt)
(1)python open_api_server.py #modification to use local model dir and 2 T4 GPUs 
(1)python openai_api_request_stream_tool_calls.py
(2)saw the KeyError:
...
tool_calls:
 [{'id': '', 'type': 'function', 'function': {'name': 'get_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weather', 'arguments': '{"location": "San Francisco, CA", "unit": "fahrenheit"}'}}]
Traceback (most recent call last):
  File "/home/techplus-820/w/GLM-4/basic_demo/openai_api_request_stream_tool_calls.py", line 144, in <module>
    print(run_conversation())
  File "/home/techplus-820/w/GLM-4/basic_demo/openai_api_request_stream_tool_calls.py", line 116, in run_conversation
    function_to_call = available_functions[function_name]
KeyError: 'get_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weatherget_current_weather'

### Expected behavior / 期待表现

final function name in tool_calls should be "get_current_weather".

**Comment by hushuitian** [comment]
The client code is from openai community and it works perfectly with fireworks firefunction-v1 that is compatible with openai tool_calls.

**Comment by jymsy** [comment]
same problem when stream call

**Comment by hushuitian** [comment]
FYI.
when using openai model="gpt-3.5-turbo-0125" and openai api_key instead in the client code, the below results are printed:  
delta:
 ChoiceDelta(content=None, function_call=None, role='assistant', tool_calls=[ChoiceDeltaToolCall(index=0, id='call_a0cR20ETdLKIZWyZqZyKH7yY', function=ChoiceDeltaToolCallFunction(arguments='', name='get_current_weather'), type='function')])
delta:
 ChoiceDelta(content=None, function_call=None, role=None, tool_calls=[ChoiceDeltaToolCall(index=0, id=None, function=ChoiceDeltaToolCallFunction(arguments='{"', name=None), type=None)])
delta:
 ChoiceDelta(content=None, function_call=None, role=None, tool_calls=[ChoiceDeltaToolCall(index=0, id=None, function=ChoiceDeltaToolCallFunction(arguments='location', name=None), type=None)])
delta:
 ChoiceDelta(content=None, function_call=None, role=None, tool_calls=[ChoiceDeltaToolCall(index=0, id=None, function=ChoiceDeltaToolCallFunction(arguments='":"', name=None), type=None)])
delta:
 ChoiceDelta(content=None, function_call=None, role=None, tool_calls=[ChoiceDeltaToolCall(index=0, id=None, function=ChoiceDeltaToolCallFunction(arguments='San', name=None), type=None)])
delta:
 ChoiceDelta(content=None, function_call=None, role=None, tool_calls=[ChoiceDeltaToolCall(index=0, id=None, function=ChoiceDeltaToolCallFunction(arguments=' Francisco', name=None), type=None)])
delta:
 ChoiceDelta(content=None, function_call=None, role=None, tool_calls=[ChoiceDeltaToolCall(index=0, id=None, function=ChoiceDeltaToolCallFunction(arguments='","', name=None), type=None)])
delta:
 ChoiceDelta(content=None, function_call=None, role=None, tool_calls=[ChoiceDeltaToolCall(index=0, id=None, function=ChoiceDeltaToolCallFunction(arguments='unit', name=None), type=None)])
delta:
 ChoiceDelta(content=None, function_call=None, role=None, tool_calls=[ChoiceDeltaToolCall(index=0, id=None, function=ChoiceDeltaToolCallFunction(arguments='":"', name=None), type=None)])
delta:
 ChoiceDelta(content=None, function_call=None, role=None, tool_calls=[ChoiceDeltaToolCall(index=0, id=None, function=ChoiceDeltaToolCallFunction(arguments='f', name=None), type=None)])
delta:
 ChoiceDelta(content=None, function_call=None, role=None, tool_calls=[ChoiceDeltaToolCall(index=0, id=None, function=ChoiceDeltaToolCallFunction(arguments='ahrenheit', name=None), type=None)])
delta:
 ChoiceDelta(content=None, function_call=None, role=None, tool_calls=[ChoiceDeltaToolCall(index=0, id=None, function=ChoiceDeltaToolCallFunction(arguments='"}', name=None), type=None)])
delta:
 ChoiceDelta(content=None, function_call=None, role=None, tool_calls=None)
tool_calls:
 [{'id': 'call_a0cR20ETdLKIZWyZqZyKH7yY', 'type': 'function', 'function': {'name': 'get_current_weather', 'arguments': '{"location":"San Francisco","unit":"fahrenheit"}'}}]
messages:
 [{'role': 'user', 'content': "Tell me what's the fahrenheit temperature in San Francisco?"}, {'tool_calls': [{'id': 'call_a0cR20ETdLKIZWyZqZyKH7yY', 'type': 'function', 'function': {'name': 'get_current_weather', 'arguments': '{"location":"San Francisco","unit":"fahrenheit"}'}}], 'role': 'assistant'}, {'tool_call_id': 'call_a0cR20ETdLKIZWyZqZyKH7yY', 'role': 'tool', 'name': 'get_current_weather', 'content': '{"location": "San Francisco", "temperature": "32", "unit": "fahrenheit"}'}]
The current temperature in San Francisco is 32 degrees Fahrenheit.None

**Comment by zRzRzRzRzRzRzR** [comment]
切换到现在的版本试试，刚刚push了一个

**Comment by hushuitian** [comment]
glm-4's test results:
delta:
 ChoiceDelta(content=None, function_call=None, role='assistant', tool_calls=[ChoiceDeltaToolCall(index=0, id='call_DfU25035HyRrY03K6JBO94Xf', function=ChoiceDeltaToolCallFunction(arguments='', name='get_current_weather'), type='function')])
delta:
 ChoiceDelta(content=None, function_call=None, role=None, tool_calls=[ChoiceDeltaToolCall(index=0, id='call_LEN0pThnXuYgjRcJ4HQbNLJy', function=ChoiceDeltaToolCallFunction(arguments='{"', name=None), type='function')])
delta:
 ChoiceDelta(content=None, function_call=None, role=None, tool_calls=[ChoiceDeltaToolCall(index=0, id='call_6bAgqnOvlFcg9mwTZ4kP7dP0', function=ChoiceDeltaToolCallFunction(arguments='location', name=None), type='function')])
delta:
 ChoiceDelta(content=None, function_call=None, role=None, tool_calls=[ChoiceDeltaToolCall(index=0, id='call_aQ324OyOjQCeTHiVDLPK30it', function=ChoiceDeltaToolCallFunction(arguments='":', name=None), type='function')])
delta:
 ChoiceDelta(content=None, function_call=None, role=None, tool_calls=[ChoiceDeltaToolCall(index=0, id='call_nBSP2b2JVRkdRB24LacuZdZ8', function=ChoiceDeltaToolCallFunction(arguments=' "', name=None), type='function')])
delta:
 ChoiceDelta(content=None, function_call=None, role=None, tool_calls=[ChoiceDeltaToolCall(index=0, id='call_SaZGghO2r8g0yfrCX1iGOv2r', function=ChoiceDeltaToolCallFunction(arguments='San', name=None), type='function')])
delta:
 ChoiceDelta(content=None, function_call=None, role=None, tool_calls=[ChoiceDeltaToolCall(index=0, id='call_I664cUROS3NxHmKajuWSuMck', function=ChoiceDeltaToolCallFunction(arguments=' Francisco', name=None), type='function')])
delta:
 ChoiceDelta(content=None, function_call=None, role=None, tool_calls=[ChoiceDeltaToolCall(index=0, id='call_hT5t1TsZsgIDuXYhhEcuQjkI', function=ChoiceDeltaToolCallFunction(arguments=',', name=None), type='function')])
delta:
 ChoiceDelta(content=None, function_call=None, role=None, tool_calls=[ChoiceDeltaToolCall(index=0, id='call_UdayGBEKQAw9qWAwd1R3BPhy', function=ChoiceDeltaToolCallFunction(arguments=' CA', name=None), type='function')])
delta:
 ChoiceDelta(content=None, function_call=None, role=None, tool_calls=[ChoiceDeltaToolCall(index=0, id='call_gCwZgKEINAGQ3Z9N2H5aRUtt', function=ChoiceDeltaToolCallFunction(arguments='",', name=None), type='function')])
delta:
 ChoiceDelta(content=None, function_call=None, role=None, tool_calls=[ChoiceDeltaToolCall(index=0, id='call_ef1cnca0ujjO8F3FJQXU9U4m', function=ChoiceDeltaToolCallFunction(arguments=' "', name=None), type='function')])
delta:
 ChoiceDelta(content=None, function_call=None, role=None, tool_calls=[ChoiceDeltaToolCall(index=0, id='call_TsJuEqZVxxk6oTu6Di3LfRYv', function=ChoiceDeltaToolCallFunction(arguments='unit', name=None), type='function')])
delta:
 ChoiceDelta(content=None, function_call=None, role=None, tool_calls=[ChoiceDeltaToolCall(index=0, id='call_gWbLiuROmWWgdRM5O8Ss07ys', function=ChoiceDeltaToolCallFunction(arguments='":', name=None), type='function')])
delta:
 ChoiceDelta(content=None, function_call=None, role=None, tool_calls=[ChoiceDeltaToolCall(index=0, id='call_BUCWec5E36PJnfY3WRAshAJ5', function=ChoiceDeltaToolCallFunction(arguments=' "', name=None), type='function')])
delta:
 ChoiceDelta(content=None, function_call=None, role=None, tool_calls=[ChoiceDeltaToolCall(index=0, id='call_VTbBQb47Seewbva8Ye3mmP6h', function=ChoiceDeltaToolCallFunction(arguments='f', name=None), type='function')])
delta:
 ChoiceDelta(content=None, function_call=None, role=None, tool_calls=[ChoiceDeltaToolCall(index=0, id='call_gv7i7wDs67Nl9gKj36XtpUsA', function=ChoiceDeltaToolCallFunction(arguments='ahrenheit', name=None), type='function')])
delta:
 ChoiceDelta(content=None, function_call=None, role=None, tool_calls=[ChoiceDeltaToolCall(index=0, id='call_eeAITiANfBw6dzzTtmsD6XrI', function=ChoiceDeltaToolCallFunction(arguments='"}', name=None), type='function')])
delta:
 ChoiceDelta(content=None, function_call=None, role=None, tool_calls=[ChoiceDeltaToolCall(index=0, id='call_vGwNfUsZBCnh8sLAUfE7HzNb', function=ChoiceDeltaToolCallFunction(arguments='', name=None), type='function')])
delta:
 ChoiceDelta(content=None, function_call=None, role=None, tool_calls=None)
tool_calls:
 [{'id': 'call_DfU25035HyRrY03K6JBO94Xfcall_LEN0pThnXuYgjRcJ4HQbNLJycall_6bAgqnOvlFcg9mwTZ4kP7dP0call_aQ324OyOjQCeTHiVDLPK30itcall_nBSP2b2JVRkdRB24LacuZdZ8call_SaZGghO2r8g0yfrCX1iGOv2rcall_I664cUROS3NxHmKajuWSuMckcall_hT5t1TsZsgIDuXYhhEcuQjkIcall_UdayGBEKQAw9qWAwd1R3BPhycall_gCwZgKEINAGQ3Z9N2H5aRUttcall_ef1cnca0ujjO8F3FJQXU9U4mcall_TsJuEqZVxxk6oTu6Di3LfRYvcall_gWbLiuROmWWgdRM5O8Ss07yscall_BUCWec5E36PJnfY3WRAshAJ5call_VTbBQb47Seewbva8Ye3mmP6hcall_gv7i7wDs67Nl9gKj36XtpUsAcall_eeAITiANfBw6dzzTtmsD6XrIcall_vGwNfUsZBCnh8sLAUfE7HzNb', 'type': 'function', 'function': {'name': 'get_current_weather', 'arguments': '{"location": "San Francisco, CA", "unit": "fahrenheit"}'}}]
messages:
 [{'role': 'user', 'content': "Tell me what's the fahrenheit temperature in San Francisco?"}, {'tool_calls': [{'id': 'call_DfU25035HyRrY03K6JBO94Xfcall_LEN0pThnXuYgjRcJ4HQbNLJycall_6bAgqnOvlFcg9mwTZ4kP7dP0call_aQ324OyOjQCeTHiVDLPK30itcall_nBSP2b2JVRkdRB24LacuZdZ8call_SaZGghO2r8g0yfrCX1iGOv2rcall_I664cUROS3NxHmKajuWSuMckcall_hT5t1TsZsgIDuXYhhEcuQjkIcall_UdayGBEKQAw9qWAwd1R3BPhycall_gCwZgKEINAGQ3Z9N2H5aRUttcall_ef1cnca0ujjO8F3FJQXU9U4mcall_TsJuEqZVxxk6oTu6Di3LfRYvcall_gWbLiuROmWWgdRM5O8Ss07yscall_BUCWec5E36PJnfY3WRAshAJ5call_VTbBQb47Seewbva8Ye3mmP6hcall_gv7i7wDs67Nl9gKj36XtpUsAcall_eeAITiANfBw6dzzTtmsD6XrIcall_vGwNfUsZBCnh8sLAUfE7HzNb', 'type': 'function', 'function': {'name': 'get_current_weather', 'arguments': '{"location": "San Francisco, CA", "unit": "fahrenheit"}'}}], 'role': 'assistant'}, {'tool_call_id': 'call_DfU25035HyRrY03K6JBO94Xfcall_LEN0pThnXuYgjRcJ4HQbNLJycall_6bAgqnOvlFcg9mwTZ4kP7dP0call_aQ324OyOjQCeTHiVDLPK30itcall_nBSP2b2JVRkdRB24LacuZdZ8call_SaZGghO2r8g0yfrCX1iGOv2rcall_I664cUROS3NxHmKajuWSuMckcall_hT5t1TsZsgIDuXYhhEcuQjkIcall_UdayGBEKQAw9qWAwd1R3BPhycall_gCwZgKEINAGQ3Z9N2H5aRUttcall_ef1cnca0ujjO8F3FJQXU9U4mcall_TsJuEqZVxxk6oTu6Di3LfRYvcall_gWbLiuROmWWgdRM5O8Ss07yscall_BUCWec5E36PJnfY3WRAshAJ5call_VTbBQb47Seewbva8Ye3mmP6hcall_gv7i7wDs67Nl9gKj36XtpUsAcall_eeAITiANfBw6dzzTtmsD6XrIcall_vGwNfUsZBCnh8sLAUfE7HzNb', 'role': 'tool', 'name': 'get_current_weather', 'content': '{"location": "San Francisco", "temperature": "32", "unit": "fahrenheit"}'}]
Traceback (most recent call last):
  File "/home/techplus-820/w/GLM-4/basic_demo/openai_api_request_stream_tool_calls.py", line 147, in <module>
    print(run_conversation())
  File "/home/techplus-820/w/GLM-4/basic_demo/openai_api_request_stream_tool_calls.py", line 136, in run_conversation
    stream = client.chat.completions.create(
  File "/home/techplus-820/.local/lib/python3.10/site-packages/openai/_utils/_utils.py", line 277, in wrapper
    return func(*args, **kwargs)
  File "/home/techplus-820/.local/lib/python3.10/site-packages/openai/resources/chat/completions.py", line 606, in create
    return self._post(
  File "/home/techplus-820/.local/lib/python3.10/site-packages/openai/_base_client.py", line 1240, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/techplus-820/.local/lib/python3.10/site-packages/openai/_base_client.py", line 921, in request
    return self._request(
  File "/home/techplus-820/.local/lib/python3.10/site-packages/openai/_base_client.py", line 1005, in _request
    return self._retry_request(
  File "/home/techplus-820/.local/lib/python3.10/site-packages/openai/_base_client.py", line 1053, in _retry_request
    return self._request(
  File "/home/techplus-820/.local/lib/python3.10/site-packages/openai/_base_client.py", line 1005, in _request
    return self._retry_request(
  File "/home/techplus-820/.local/lib/python3.10/site-packages/openai/_base_client.py", line 1053, in _retry_request
    return self._request(
  File "/home/techplus-820/.local/lib/python3.10/site-packages/openai/_base_client.py", line 1020, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.InternalServerError: Internal Server Error

**Comment by hushuitian** [comment]
gpt-3.5-turbo-0125's test results:
delta:
 ChoiceDelta(content=None, function_call=None, role='assistant', tool_calls=[ChoiceDeltaToolCall(index=0, id='call_ymApqEQkT5NrUeIKZPGoFLR4', function=ChoiceDeltaToolCallFunction(arguments='', name='get_current_weather'), type='function')])
delta:
 ChoiceDelta(content=None, function_call=None, role=None, tool_calls=[ChoiceDeltaToolCall(index=0, id=None, function=ChoiceDeltaToolCallFunction(arguments='{"', name=None), type=None)])
delta:
 ChoiceDelta(content=None, function_call=None, role=None, tool_calls=[ChoiceDeltaToolCall(index=0, id=None, function=ChoiceDeltaToolCallFunction(arguments='location', name=None), type=None)])
delta:
 ChoiceDelta(content=None, function_call=None, role=None, tool_calls=[ChoiceDeltaToolCall(index=0, id=None, function=ChoiceDeltaToolCallFunction(arguments='":"', name=None), type=None)])
delta:
 ChoiceDelta(content=None, function_call=None, role=None, tool_calls=[ChoiceDeltaToolCall(index=0, id=None, function=ChoiceDeltaToolCallFunction(arguments='San', name=None), type=None)])
delta:
 ChoiceDelta(content=None, function_call=None, role=None, tool_calls=[ChoiceDeltaToolCall(index=0, id=None, function=ChoiceDeltaToolCallFunction(arguments=' Francisco', name=None), type=None)])
delta:
 ChoiceDelta(content=None, function_call=None, role=None, tool_calls=[ChoiceDeltaToolCall(index=0, id=None, function=ChoiceDeltaToolCallFunction(arguments=',', name=None), type=None)])
delta:
 ChoiceDelta(content=None, function_call=None, role=None, tool_calls=[ChoiceDeltaToolCall(index=0, id=None, function=ChoiceDeltaToolCallFunction(arguments=' CA', name=None), type=None)])
delta:
 ChoiceDelta(content=None, function_call=None, role=None, tool_calls=[ChoiceDeltaToolCall(index=0, id=None, function=ChoiceDeltaToolCallFunction(arguments='","', name=None), type=None)])
delta:
 ChoiceDelta(content=None, function_call=None, role=None, tool_calls=[ChoiceDeltaToolCall(index=0, id=None, function=ChoiceDeltaToolCallFunction(arguments='unit', name=None), type=None)])
delta:
 ChoiceDelta(content=None, function_call=None, role=None, tool_calls=[ChoiceDeltaToolCall(index=0, id=None, function=ChoiceDeltaToolCallFunction(arguments='":"', name=None), type=None)])
delta:
 ChoiceDelta(content=None, function_call=None, role=None, tool_calls=[ChoiceDeltaToolCall(index=0, id=None, function=ChoiceDeltaToolCallFunction(arguments='f', name=None), type=None)])
delta:
 ChoiceDelta(content=None, function_call=None, role=None, tool_calls=[ChoiceDeltaToolCall(index=0, id=None, function=ChoiceDeltaToolCallFunction(arguments='ahrenheit', name=None), type=None)])
delta:
 ChoiceDelta(content=None, function_call=None, role=None, tool_calls=[ChoiceDeltaToolCall(index=0, id=None, function=ChoiceDeltaToolCallFunction(arguments='"}', name=None), type=None)])
delta:
 ChoiceDelta(content=None, function_call=None, role=None, tool_calls=None)
tool_calls:
 [{'id': 'call_ymApqEQkT5NrUeIKZPGoFLR4', 'type': 'function', 'function': {'name': 'get_current_weather', 'arguments': '{"location":"San Francisco, CA","unit":"fahrenheit"}'}}]
messages:
 [{'role': 'user', 'content': "Tell me what's the fahrenheit temperature in San Francisco?"}, {'tool_calls': [{'id': 'call_ymApqEQkT5NrUeIKZPGoFLR4', 'type': 'function', 'function': {'name': 'get_current_weather', 'arguments': '{"location":"San Francisco, CA","unit":"fahrenheit"}'}}], 'role': 'assistant'}, {'tool_call_id': 'call_ymApqEQkT5NrUeIKZPGoFLR4', 'role': 'tool', 'name': 'get_current_weather', 'content': '{"location": "San Francisco", "temperature": "32", "unit": "fahrenheit"}'}]
The current temperature in San Francisco is 32 degrees Fahrenheit.None

**Comment by hushuitian** [comment]
It seems that there is still a minor issue on id of glm-4 server. It should work if the id issue is handled correctly.

**Comment by zRzRzRzRzRzRzR** [comment]
The current ID is a randomly generated ID. Could you provide some detailed reasons for the ID issues?

**Comment by hushuitian** [comment]
@zRzRzRzRzRzRzR 
Please compare the test results from glm-4 server and from gpt-3.5 as above.
glm-4 server generated a random id on every ChoiceDelta. gpt-3.5 only generated a random id on the 1st ChoiceDelta and generated id=None on the following ChoiceDelta.

**Comment by zRzRzRzRzRzRzR** [comment]
fix

**Comment by hushuitian** [comment]
printed logs from openai_api_request_stream_tool_calls.py:
delta:
 ChoiceDelta(content=None, function_call=None, role='assistant', tool_calls=[ChoiceDeltaToolCall(index=0, id='call_DfU25035HyRrY03K6JBO94Xf', function=ChoiceDeltaToolCallFunction(arguments='', name='get_current_weather'), type='function')])
delta:
 ChoiceDelta(content=None, function_call=None, role=None, tool_calls=[ChoiceDeltaToolCall(index=0, id=None, function=ChoiceDeltaToolCallFunction(arguments='{"', name=None), type='function')])
delta:
 ChoiceDelta(content=None, function_call=None, role=None, tool_calls=[ChoiceDeltaToolCall(index=0, id=None, function=ChoiceDeltaToolCallFunction(arguments='location', name=None), type='function')])
delta:
 ChoiceDelta(content=None, function_call=None, role=None, tool_calls=[ChoiceDeltaToolCall(index=0, id=None, function=ChoiceDeltaToolCallFunction(arguments='":', name=None), type='function')])
delta:
 ChoiceDelta(content=None, function_call=None, role=None, tool_calls=[ChoiceDeltaToolCall(index=0, id=None, function=ChoiceDeltaToolCallFunction(arguments=' "', name=None), type='function')])
delta:
 ChoiceDelta(content=None, function_call=None, role=None, tool_calls=[ChoiceDeltaToolCall(index=0, id=None, function=ChoiceDeltaToolCallFunction(arguments='San', name=None), type='function')])
delta:
 ChoiceDelta(content=None, function_call=None, role=None, tool_calls=[ChoiceDeltaToolCall(index=0, id=None, function=ChoiceDeltaToolCallFunction(arguments=' Francisco', name=None), type='function')])
delta:
 ChoiceDelta(content=None, function_call=None, role=None, tool_calls=[ChoiceDeltaToolCall(index=0, id=None, function=ChoiceDeltaToolCallFunction(arguments=',', name=None), type='function')])
delta:
 ChoiceDelta(content=None, function_call=None, role=None, tool_calls=[ChoiceDeltaToolCall(index=0, id=None, function=ChoiceDeltaToolCallFunction(arguments=' CA', name=None), type='function')])
delta:
 ChoiceDelta(content=None, function_call=None, role=None, tool_calls=[ChoiceDeltaToolCall(index=0, id=None, function=ChoiceDeltaToolCallFunction(arguments='",', name=None), type='function')])
delta:
 ChoiceDelta(content=None, function_call=None, role=None, tool_calls=[ChoiceDeltaToolCall(index=0, id=None, function=ChoiceDeltaToolCallFunction(arguments=' "', name=None), type='function')])
delta:
 ChoiceDelta(content=None, function_call=None, role=None, tool_calls=[ChoiceDeltaToolCall(index=0, id=None, function=ChoiceDeltaToolCallFunction(arguments='unit', name=None), type='function')])
delta:
 ChoiceDelta(content=None, function_call=None, role=None, tool_calls=[ChoiceDeltaToolCall(index=0, id=None, function=ChoiceDeltaToolCallFunction(arguments='":', name=None), type='function')])
delta:
 ChoiceDelta(content=None, function_call=None, role=None, tool_calls=[ChoiceDeltaToolCall(index=0, id=None, function=ChoiceDeltaToolCallFunction(arguments=' "', name=None), type='function')])
delta:
 ChoiceDelta(content=None, function_call=None, role=None, tool_calls=[ChoiceDeltaToolCall(index=0, id=None, function=ChoiceDeltaToolCallFunction(arguments='f', name=None), type='function')])
delta:
 ChoiceDelta(content=None, function_call=None, role=None, tool_calls=[ChoiceDeltaToolCall(index=0, id=None, function=ChoiceDeltaToolCallFunction(arguments='ahrenheit', name=None), type='function')])
delta:
 ChoiceDelta(content=None, function_call=None, role=None, tool_calls=[ChoiceDeltaToolCall(index=0, id=None, function=ChoiceDeltaToolCallFunction(arguments='"}', name=None), type='function')])
delta:
 ChoiceDelta(content=None, function_call=None, role=None, tool_calls=[ChoiceDeltaToolCall(index=0, id=None, function=ChoiceDeltaToolCallFunction(arguments='', name=None), type='function')])
delta:
 ChoiceDelta(content=None, function_call=None, role=None, tool_calls=None)
tool_calls:
 [{'id': 'call_DfU25035HyRrY03K6JBO94Xf', 'type': 'function', 'function': {'name': 'get_current_weather', 'arguments': '{"location": "San Francisco, CA", "unit": "fahrenheit"}'}}]
messages:
 [{'role': 'user', 'content': "Tell me what's the fahrenheit temperature in San Francisco?"}, {'tool_calls': [{'id': 'call_DfU25035HyRrY03K6JBO94Xf', 'type': 'function', 'function': {'name': 'get_current_weather', 'arguments': '{"location": "San Francisco, CA", "unit": "fahrenheit"}'}}], 'role': 'assistant'}, {'tool_call_id': 'call_DfU25035HyRrY03K6JBO94Xf', 'role': 'tool', 'name': 'get_current_weather', 'content': '{"location": "San Francisco", "temperature": "32", "unit": "fahrenheit"}'}]
Traceback (most recent call last):
  File "/home/techplus-820/w/GLM-4/basic_demo/openai_api_request_stream_tool_calls.py", line 148, in <module>
    print(run_conversation())
  File "/home/techplus-820/w/GLM-4/basic_demo/openai_api_request_stream_tool_calls.py", line 137, in run_conversation
    stream = client.chat.completions.create(
  File "/home/techplus-820/.local/lib/python3.10/site-packages/openai/_utils/_utils.py", line 277, in wrapper
    return func(*args, **kwargs)
  File "/home/techplus-820/.local/lib/python3.10/site-packages/openai/resources/chat/completions.py", line 606, in create
    return self._post(
  File "/home/techplus-820/.local/lib/python3.10/site-packages/openai/_base_client.py", line 1240, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/techplus-820/.local/lib/python3.10/site-packages/openai/_base_client.py", line 921, in request
    return self._request(
  File "/home/techplus-820/.local/lib/python3.10/site-packages/openai/_base_client.py", line 1005, in _request
    return self._retry_request(
  File "/home/techplus-820/.local/lib/python3.10/site-packages/openai/_base_client.py", line 1053, in _retry_request
    return self._request(
  File "/home/techplus-820/.local/lib/python3.10/site-packages/openai/_base_client.py", line 1005, in _request
    return self._retry_request(
  File "/home/techplus-820/.local/lib/python3.10/site-packages/openai/_base_client.py", line 1053, in _retry_request
    return self._request(
  File "/home/techplus-820/.local/lib/python3.10/site-packages/openai/_base_client.py", line 1020, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.InternalServerError: Internal Server Error

**Comment by hushuitian** [comment]
printed logs from openai_api_server.py:
...
INFO:     127.0.0.1:50848 - "POST /v1/chat/completions HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/techplus-820/.local/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 411, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/techplus-820/.local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
  File "/home/techplus-820/.local/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/techplus-820/.local/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/techplus-820/.local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/home/techplus-820/.local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/home/techplus-820/.local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "/home/techplus-820/.local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/techplus-820/.local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/techplus-820/.local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/techplus-820/.local/lib/python3.10/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/techplus-820/.local/lib/python3.10/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/home/techplus-820/.local/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/home/techplus-820/.local/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/techplus-820/.local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/techplus-820/.local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/techplus-820/.local/lib/python3.10/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
  File "/home/techplus-820/.local/lib/python3.10/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
  File "/home/techplus-820/.local/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/techplus-820/w/GLM-4/basic_demo/openai_api_server.py", line 366, in create_chat_completion
    output = await anext(predict_stream_generator)
  File "/home/techplus-820/w/GLM-4/basic_demo/openai_api_server.py", line 448, in predict_stream
    tools = {tool['function']['name'] for tool in gen_params['tools']}
TypeError: 'NoneType' object is not iterable

**Comment by hushuitian** [comment]
@zRzRzRzRzRzRzR  Thak your very much! I really appreciate your real-time fixing! I believe tool_calls and messages are correct now. But there is still a little issue need to be fixed.
According to printed logs(see above) from client and latest version server, I guess server need to handle the 
last ChoiceDelta carefully and differently:
...
ChoiceDelta(content=None, function_call=None, role=None, tool_calls=None)
...   
I suspect some None value in the last ChoiceDelta caused the 500 Internal Server Error!

**Comment by hushuitian** [comment]
FYI.
In predict_stream(), change:
 
tools = {tool['function']['name'] for tool in gen_params['tools']}

to: 

if gen_params['tools'] != None:
      tools = {tool['function']['name'] for tool in gen_params['tools']}
else:
      tools = None

It seems work!

**Comment by hushuitian** [comment]
In the same predict_stream(),also having to do another change as below:
#if first_line in tools:
if tools != None and first_line in tools:
It seems that having to thoroughly check the whole server code on tools==None?

**Comment by zRzRzRzRzRzRzR** [comment]
<img width="873" alt="image" src="https://github.com/THUDM/GLM-4/assets/93239683/2b014770-465f-4255-a6ba-052fbb8447b3">

change to this to fix it
