### ISSUE TITLE
run  openai_api_server.py  and chat with error

### ISSUE THREAD

**Issue by yuanzhiwei** [THUDM/GLM-4#205]
(VllmWorkerProcess pid=1863062) INFO 06-18 22:24:07 selector.py:131] Cannot use FlashAttention-2 backend for Volta and Turing GPUs.
(VllmWorkerProcess pid=1863063) INFO 06-18 22:24:07 selector.py:131] Cannot use FlashAttention-2 backend for Volta and Turing GPUs.
(VllmWorkerProcess pid=1863063) INFO 06-18 22:24:07 selector.py:51] Using XFormers backend.
(VllmWorkerProcess pid=1863062) INFO 06-18 22:24:07 selector.py:51] Using XFormers backend.
(VllmWorkerProcess pid=1863063) INFO 06-18 22:24:25 model_runner.py:160] Loading model weights took 4.4372 GB
INFO 06-18 22:24:25 model_runner.py:160] Loading model weights took 4.4372 GB
(VllmWorkerProcess pid=1863062) INFO 06-18 22:24:25 model_runner.py:160] Loading model weights took 4.4372 GB
(VllmWorkerProcess pid=1863064) INFO 06-18 22:24:25 model_runner.py:160] Loading model weights took 4.4372 GB
INFO 06-18 22:24:28 distributed_gpu_executor.py:56] # GPU blocks: 62704, # CPU blocks: 13107
INFO:     Started server process [1860406]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     10.2.0.3:34082 - "POST /v1/chat/completions HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/data/software/.pyenv/versions/3.10.0/envs/glm-4/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/data/software/.pyenv/versions/3.10.0/envs/glm-4/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
  File "/data/software/.pyenv/versions/3.10.0/envs/glm-4/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/data/software/.pyenv/versions/3.10.0/envs/glm-4/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/data/software/.pyenv/versions/3.10.0/envs/glm-4/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/data/software/.pyenv/versions/3.10.0/envs/glm-4/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/data/software/.pyenv/versions/3.10.0/envs/glm-4/lib/python3.10/site-packages/starlette/middleware/cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "/data/software/.pyenv/versions/3.10.0/envs/glm-4/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/data/software/.pyenv/versions/3.10.0/envs/glm-4/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/data/software/.pyenv/versions/3.10.0/envs/glm-4/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/data/software/.pyenv/versions/3.10.0/envs/glm-4/lib/python3.10/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/data/software/.pyenv/versions/3.10.0/envs/glm-4/lib/python3.10/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/data/software/.pyenv/versions/3.10.0/envs/glm-4/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/data/software/.pyenv/versions/3.10.0/envs/glm-4/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/data/software/.pyenv/versions/3.10.0/envs/glm-4/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/data/software/.pyenv/versions/3.10.0/envs/glm-4/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/data/software/.pyenv/versions/3.10.0/envs/glm-4/lib/python3.10/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
  File "/data/software/.pyenv/versions/3.10.0/envs/glm-4/lib/python3.10/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
  File "/data/software/.pyenv/versions/3.10.0/envs/glm-4/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/data/models/glm4_openai_server.py", line 365, in create_chat_completion
    output = await anext(predict_stream_generator)
  File "/data/models/glm4_openai_server.py", line 447, in predict_stream
    tools = {tool['function']['name'] for tool in gen_params['tools']}
TypeError: 'NoneType' object is not iterable

**Comment by yuanzhiwei** [comment]
openai_api_server.py and  requirements.txt is the latest

**Comment by yuanzhiwei** [comment]
![image](https://github.com/THUDM/GLM-4/assets/17841347/c22dc28b-4007-478f-92c4-6a7d97fb18b0)
大佬 , 我更新了代码 , 还是这个错误
