### ISSUE TITLE
model(**batch)报错

### ISSUE THREAD

**Issue by Zbaoli** [THUDM/GLM-4#25]
### System Info / 系統信息

deepspeed==0.14.2
torch==2.3.0
transformers==4.41.2

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

调用`model(**batch)`报错：
batch：
```
{'input_ids': tensor([[151331, 151333, 151331,  ...,      0,      0,      0],                                                                                                   
        [151331, 151333, 151331,  ...,      0,      0,      0],                                                                                                                 
        [151331, 151333, 151331,  ...,      0,      0,      0],
        ...,
        [151331, 151333, 151331,  ...,      0,      0,      0],
        [151331, 151333, 151331,  ...,      0,      0,      0],
        [151331, 151333, 151331,  ..., 114689,  99153, 151329]]), 'labels': tensor([[151331, 151333, 151331,  ...,      0,      0,      0],
        [151331, 151333, 151331,  ...,      0,      0,      0],
        [151331, 151333, 151331,  ...,      0,      0,      0],
        ...,
        [151331, 151333, 151331,  ...,      0,      0,      0],
        [151331, 151333, 151331,  ...,      0,      0,      0],
        [151331, 151333, 151331,  ..., 114689,  99153, 151329]]), 'attention_mask': tensor([[ True,  True,  True,  ..., False, False, False],
        [ True,  True,  True,  ..., False, False, False],
        [ True,  True,  True,  ..., False, False, False],
        ...,
        [ True,  True,  True,  ..., False, False, False],
        [ True,  True,  True,  ..., False, False, False],
        [ True,  True,  True,  ...,  True,  True, False]])}
```
报错信息：
```
Traceback (most recent call last):                                                                                                                                              
  File "<console>", line 1, in <module>                                                                                                                                         
  File "/root/anaconda3/envs/pytorch_build/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl                                            
    return self._call_impl(*args, **kwargs)                                             
  File "/root/anaconda3/envs/pytorch_build/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl                                                    
    return forward_call(*args, **kwargs)                                                                                                                                        
  File "/root/anaconda3/envs/pytorch_build/lib/python3.9/site-packages/accelerate/hooks.py", line 166, in new_forward           
    output = module._old_forward(*args, **kwargs)                                                                                                                               
  File "/root/.cache/huggingface/modules/transformers_modules/glm-4-9b-chat/modeling_chatglm.py", line 881, in forward                            
    transformer_outputs = self.transformer(                                                                                                                                     
  File "/root/anaconda3/envs/pytorch_build/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl                                            
    return self._call_impl(*args, **kwargs)                                                                                                                                     
  File "/root/anaconda3/envs/pytorch_build/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl                                                    
    return forward_call(*args, **kwargs)                                                                                                                                        
  File "/root/.cache/huggingface/modules/transformers_modules/glm-4-9b-chat/modeling_chatglm.py", line 767, in forward                                                          
    full_attention_mask = self.get_masks(input_ids, past_key_values, padding_mask=attention_mask)                                                                               
  File "/root/.cache/huggingface/modules/transformers_modules/glm-4-9b-chat/modeling_chatglm.py", line 668, in get_masks                    
    full_attention_mask -= padding_mask.unsqueeze(-1) - 1                                                                                                                       
RuntimeError: Subtraction, the `-` operator, with a bool tensor is not supported. If you are trying to invert a mask, use the `~` or `logical_not()` operator instead.       
```

### Expected behavior / 期待表现

希望不会报错

**Comment by Zbaoli** [comment]
看了下是在output = model(**batch)这一步报错的
batch：
```
{'input_ids': tensor([[151331, 151333, 151331,  ...,      0,      0,      0],                                                                                                   
        [151331, 151333, 151331,  ...,      0,      0,      0],                                                                                                                 
        [151331, 151333, 151331,  ...,      0,      0,      0],
        ...,
        [151331, 151333, 151331,  ...,      0,      0,      0],
        [151331, 151333, 151331,  ...,      0,      0,      0],
        [151331, 151333, 151331,  ..., 114689,  99153, 151329]]), 'labels': tensor([[151331, 151333, 151331,  ...,      0,      0,      0],
        [151331, 151333, 151331,  ...,      0,      0,      0],
        [151331, 151333, 151331,  ...,      0,      0,      0],
        ...,
        [151331, 151333, 151331,  ...,      0,      0,      0],
        [151331, 151333, 151331,  ...,      0,      0,      0],
        [151331, 151333, 151331,  ..., 114689,  99153, 151329]]), 'attention_mask': tensor([[ True,  True,  True,  ..., False, False, False],
        [ True,  True,  True,  ..., False, False, False],
        [ True,  True,  True,  ..., False, False, False],
        ...,
        [ True,  True,  True,  ..., False, False, False],
        [ True,  True,  True,  ..., False, False, False],
        [ True,  True,  True,  ...,  True,  True, False]])}
```
报错信息：
```
Traceback (most recent call last):                                                                                                                                              
  File "<console>", line 1, in <module>                                                                                                                                         
  File "/root/anaconda3/envs/pytorch_build/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl                                            
    return self._call_impl(*args, **kwargs)                                             
  File "/root/anaconda3/envs/pytorch_build/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl                                                    
    return forward_call(*args, **kwargs)                                                                                                                                        
  File "/root/anaconda3/envs/pytorch_build/lib/python3.9/site-packages/accelerate/hooks.py", line 166, in new_forward           
    output = module._old_forward(*args, **kwargs)                                                                                                                               
  File "/root/.cache/huggingface/modules/transformers_modules/glm-4-9b-chat/modeling_chatglm.py", line 881, in forward                            
    transformer_outputs = self.transformer(                                                                                                                                     
  File "/root/anaconda3/envs/pytorch_build/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl                                            
    return self._call_impl(*args, **kwargs)                                                                                                                                     
  File "/root/anaconda3/envs/pytorch_build/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl                                                    
    return forward_call(*args, **kwargs)                                                                                                                                        
  File "/root/.cache/huggingface/modules/transformers_modules/glm-4-9b-chat/modeling_chatglm.py", line 767, in forward                                                          
    full_attention_mask = self.get_masks(input_ids, past_key_values, padding_mask=attention_mask)                                                                               
  File "/root/.cache/huggingface/modules/transformers_modules/glm-4-9b-chat/modeling_chatglm.py", line 668, in get_masks                    
    full_attention_mask -= padding_mask.unsqueeze(-1) - 1                                                                                                                       
RuntimeError: Subtraction, the `-` operator, with a bool tensor is not supported. If you are trying to invert a mask, use the `~` or `logical_not()` operator instead.       
```

**Comment by Zbaoli** [comment]
没人遇到这个问题嘛😳

**Comment by ChengjieLi28** [comment]
@Zbaoli 你好，我也遇到这个问题了，直接调用模型model(**batch, attention_mask=<my_attention_mask>)，传入维度大于1的batch tensor，会报：
<img width="1661" alt="image" src="https://github.com/THUDM/GLM-4/assets/109656400/0b4a7db5-a9a9-43b2-aeda-7ef095a762c5">
请问你解决了吗？
@zRzRzRzRzRzRzR 请问有什么解决方案吗？

**Comment by zRzRzRzRzRzRzR** [comment]
你是batch 输入吗，或许你应该看我们的batch input 的demo

**Comment by ChengjieLi28** [comment]
> 你是batch 输入吗，或许你应该看我们的batch input 的demo

demo中需要调用`model.generate`，看起来这个接口是支持batch输入的。
请问下transfomers加载后model本身的__call__接收batch输入需要如何修改？另外，如果我不用attention_mask，__call__可以接受batch输入，但是效果很差（有乱说话和重复输出的现象，padding部分的影响应该是）。

**Comment by zRzRzRzRzRzRzR** [comment]
trans_batch_demo.py就是没有调用attention_mask的
model.generate 函数可以处理批量输入，自动处理 attention_mask 和 padding，
这就是为什么通常推荐使用 model.generate 而不是 model.__call__ 来生成文本。
model.__call__ 更适合用于模型的逐步前向传播，比如在训练或细粒度控制推理过程中。

**Comment by ChengjieLi28** [comment]
> trans_batch_demo.py就是没有调用attention_mask的 model.generate 函数可以处理批量输入，自动处理 attention_mask 和 padding， 这就是为什么通常推荐使用 model.generate 而不是 model.**call** 来生成文本。 model.**call** 更适合用于模型的逐步前向传播，比如在训练或细粒度控制推理过程中。

你好，我解决了__call__ batch的问题，attention mask的维度设置错了，设置对了之后，上面那个图的mask计算就能顺利通过了。多谢哈
