### ISSUE TITLE
TypeError: unsupported operand type(s) for |: 'type' and '_GenericAlias'

### ISSUE THREAD

**Issue by chuan-mt** [THUDM/GLM-4#250]
### System Info / 系統信息

python openai_api_server.py
CUDA_VISIBLE_DEVICES set to: 6
Traceback (most recent call last):
  File "/nfs2/zhaochuan.cai/czc_demo/GLM-4/basic_demo/openai_api_server.py", line 155, in <module>
    def process_response(output: str, tools: dict | List[dict] = None, use_tool: bool = False) -> Union[str, dict]:
TypeError: unsupported operand type(s) for |: 'type' and '_GenericAlias'

### Who can help? / 谁可以帮助到您？

python openai_api_server.py
CUDA_VISIBLE_DEVICES set to: 6
Traceback (most recent call last):
  File "/nfs2/zhaochuan.cai/czc_demo/GLM-4/basic_demo/openai_api_server.py", line 155, in <module>
    def process_response(output: str, tools: dict | List[dict] = None, use_tool: bool = False) -> Union[str, dict]:
TypeError: unsupported operand type(s) for |: 'type' and '_GenericAlias'

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

python openai_api_server.py
CUDA_VISIBLE_DEVICES set to: 6
Traceback (most recent call last):
  File "/nfs2/zhaochuan.cai/czc_demo/GLM-4/basic_demo/openai_api_server.py", line 155, in <module>
    def process_response(output: str, tools: dict | List[dict] = None, use_tool: bool = False) -> Union[str, dict]:
TypeError: unsupported operand type(s) for |: 'type' and '_GenericAlias'

### Expected behavior / 期待表现

python openai_api_server.py
CUDA_VISIBLE_DEVICES set to: 6
Traceback (most recent call last):
  File "/nfs2/zhaochuan.cai/czc_demo/GLM-4/basic_demo/openai_api_server.py", line 155, in <module>
    def process_response(output: str, tools: dict | List[dict] = None, use_tool: bool = False) -> Union[str, dict]:
TypeError: unsupported operand type(s) for |: 'type' and '_GenericAlias'

**Comment by zRzRzRzRzRzRzR** [comment]
这个是python版本太低了么，我们用的是python3.10
