### ISSUE TITLE
文档解读时出现错误

### ISSUE THREAD

**Issue by liangdaojun** [THUDM/GLM-4#259]
### System Info / 系統信息

请问我在文档解读时，上传一篇论文后，让glm4总结一下，老是出现错误怎么回事，我的卡是8个32G的。
错误如下：
Traceback (most recent call last):
  File "/nfs/glm/GLM-4/composite_demo/src/main.py", line 288, in main
    for response, chat_history in client.generate_stream(
  File "/nfs/glm/GLM-4/composite_demo/src/clients/hf.py", line 57, in generate_stream
    for token_text in streamer:
  File "/home/user/anaconda3/envs/GLM4/lib/python3.10/site-packages/transformers/generation/streamers.py", line 223, in __next__
    value = self.text_queue.get(timeout=self.timeout)
  File "/home/user/anaconda3/envs/GLM4/lib/python3.10/queue.py", line 179, in get
    raise Empty
_queue.Empty
请大佬不吝赐教^_^!

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

1. cd /composite_demo
2.   streamlit run src/main.py
3. 在网页端选择“文档解读”
4. 上传文档后出现错误

### Expected behavior / 期待表现

可正常解读文档。

**Comment by zRzRzRzRzRzRzR** [comment]
是不是少了依赖，上传的是PDF吗
