### ISSUE TITLE
glm-4-9b-chat-1m加载推理汇报错

### ISSUE THREAD

**Issue by wstsr333** [THUDM/GLM-4#263]
### System Info / 系統信息

cuda12.0 python3.11 torch2.3 显卡v100

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

使用basic_demo里面的cli运行加载glm-4-9b-chat-1m模型推理时会报如下错误：
Traceback (most recent call last):
  File "/data/glm1/glm-1m/api1.py", line 27, in <module>
    outputs = model.generate(**inputs, **gen_kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/share/virtualenvs/glm1-Z-gRxj_B/lib64/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_c
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/share/virtualenvs/glm1-Z-gRxj_B/lib/python3.11/site-packages/transformers/generation/utils.py", line 1914, in gener
    result = self._sample(
             ^^^^^^^^^^^^^
  File "/root/.local/share/virtualenvs/glm1-Z-gRxj_B/lib/python3.11/site-packages/transformers/generation/utils.py", line 2651, in _samp
    outputs = self(
              ^^^^^
  File "/root/.local/share/virtualenvs/glm1-Z-gRxj_B/lib64/python3.11/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/share/virtualenvs/glm1-Z-gRxj_B/lib64/python3.11/site-packages/torch/nn/modules/module.py", line 1541, in _call_imp
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/huggingface/modules/transformers_modules/glm-1m/modeling_chatglm.py", line 1001, in forward
    transformer_outputs = self.transformer(
                          ^^^^^^^^^^^^^^^^^
  File "/root/.local/share/virtualenvs/glm1-Z-gRxj_B/lib64/python3.11/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/share/virtualenvs/glm1-Z-gRxj_B/lib64/python3.11/site-packages/torch/nn/modules/module.py", line 1541, in _call_imp
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/huggingface/modules/transformers_modules/glm-1m/modeling_chatglm.py", line 897, in forward
    hidden_states, presents, all_hidden_states, all_self_attentions = self.encoder(
                                                                      ^^^^^^^^^^^^^
  File "/root/.local/share/virtualenvs/glm1-Z-gRxj_B/lib64/python3.11/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/share/virtualenvs/glm1-Z-gRxj_B/lib64/python3.11/site-packages/torch/nn/modules/module.py", line 1541, in _call_imp
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/huggingface/modules/transformers_modules/glm-1m/modeling_chatglm.py", line 722, in forward
    layer_ret = layer(
                ^^^^^^
  File "/root/.local/share/virtualenvs/glm1-Z-gRxj_B/lib64/python3.11/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/share/virtualenvs/glm1-Z-gRxj_B/lib64/python3.11/site-packages/torch/nn/modules/module.py", line 1541, in _call_imp
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/huggingface/modules/transformers_modules/glm-1m/modeling_chatglm.py", line 625, in forward
    attention_output, kv_cache = self.self_attention(
                                 ^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/share/virtualenvs/glm1-Z-gRxj_B/lib64/python3.11/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/share/virtualenvs/glm1-Z-gRxj_B/lib64/python3.11/site-packages/torch/nn/modules/module.py", line 1541, in _call_imp
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/huggingface/modules/transformers_modules/glm-1m/modeling_chatglm.py", line 490, in forward
    cache_k, cache_v = kv_cache
    ^^^^^^^^^^^^^^^^
ValueError: too many values to unpack (expected 2)

### Expected behavior / 期待表现

正常给出模型回复

**Comment by BigCakeLove** [comment]
这个好像是transformer版本的问题，我的上了4.42也报这个错误，降下去虽然不报错了，但是乱码，英文啥的出来了。

**Comment by BigCakeLove** [comment]
我的乱码可能是微调和推理用的transformers版本不一样，都改成4.41.2后就好了。

**Comment by zRzRzRzRzRzRzR** [comment]
改成4.40

**Comment by wstsr333** [comment]
欧克，我试试

**Comment by wstsr333** [comment]
搞定了

**Comment by Anta-chen** [comment]
有没有不降transformers版本的解决办法，其他包依赖4.42版本

**Comment by hybplayer** [comment]
> 有没有不降transformers版本的解决办法，其他包依赖4.42版本

老哥你解决了吗，我也是这个问题
