### ISSUE TITLE
openai_api_server.py报错

### ISSUE THREAD

**Issue by 1444141859** [THUDM/GLM-4#27]
### System Info / 系統信息

python=3.9，vllm=0.4.0+cu118  torch=2.1.2+cu118

### Who can help? / 谁可以帮助到您？

无

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

Traceback (most recent call last):
  File "/home/pai/envs/glm4/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 411, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/pai/envs/glm4/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
  File "/home/pai/envs/glm4/lib/python3.9/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/pai/envs/glm4/lib/python3.9/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/pai/envs/glm4/lib/python3.9/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/home/pai/envs/glm4/lib/python3.9/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/home/pai/envs/glm4/lib/python3.9/site-packages/starlette/middleware/cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "/home/pai/envs/glm4/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/pai/envs/glm4/lib/python3.9/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/pai/envs/glm4/lib/python3.9/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/pai/envs/glm4/lib/python3.9/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/pai/envs/glm4/lib/python3.9/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/home/pai/envs/glm4/lib/python3.9/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/home/pai/envs/glm4/lib/python3.9/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/pai/envs/glm4/lib/python3.9/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/pai/envs/glm4/lib/python3.9/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/pai/envs/glm4/lib/python3.9/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
  File "/home/pai/envs/glm4/lib/python3.9/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
  File "/home/pai/envs/glm4/lib/python3.9/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/mnt/workspace/GLM-4/basic_demo/openai_api_server.py", line 338, in create_chat_completion
    async for response in generate_stream_glm4(gen_params):
  File "/mnt/workspace/GLM-4/basic_demo/openai_api_server.py", line 196, in generate_stream_glm4
    async for output in engine.generate(inputs=inputs, sampling_params=sampling_params, request_id="glm-4"):
TypeError: generate() got an unexpected keyword argument 'inputs'

没有这个inputs参数？？？？

### Expected behavior / 期待表现

怎么解决

**Comment by xusenlinzy** [comment]
升级一下vllm
