### ISSUE TITLE
 报错 invalid literal for int() with base 10: 'https://git-lfs.github.com/spec/v1'

### ISSUE THREAD

**Issue by ls32140** [THUDM/GLM-4#282]
### System Info / 系統信息

cuda:12.2
python:3.10.12

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

cd basic_demo
python openai_api_server.py

### Expected behavior / 期待表现

我已经安装了git-fls, 但还是报错，这是什么问题呢
Traceback (most recent call last):
  File "/home/ubuntu/Students/liuxiu/GLM/basic_demo/openai_api_server.py", line 618, in <module>
    tokenizer = AutoTokenizer.from_pretrained(MODEL_PATH, trust_remote_code=True)
  File "/home/ubuntu/miniconda/envs/lxllm/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 847, in from_pretrained
    return tokenizer_class.from_pretrained(
  File "/home/ubuntu/miniconda/envs/lxllm/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2089, in from_pretrained
    return cls._from_pretrained(
  File "/home/ubuntu/miniconda/envs/lxllm/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2311, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/home/ubuntu/.cache/huggingface/modules/transformers_modules/glm-4-9b-chat/tokenization_chatglm.py", line 35, in __init__
    rank = int(rank)
ValueError: invalid literal for int() with base 10: 'https://git-lfs.github.com/spec/v1'

**Comment by ls32140** [comment]
我已经解决了这个问题，安装好git fls 重新下载GLM-4-9B-Chat
