### ISSUE TITLE
GLM-4V-9B推理报错

### ISSUE THREAD

**Issue by 641009368** [THUDM/GLM-4#320]
### System Info / 系統信息

模型推理时报错thread '<unnamed>' panicked at 'index out of bounds: the len is 1 but the index is 1'
(base) root@fusiontech-MS-7D70:/data/rich/project/GLM-4/basic_demo# python trans_cli_vision_demo.py
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 15/15 [00:17<00:00,  1.19s/it]
We've detected an older driver with an RTX 4000 series GPU. These drivers have issues with P2P. This can affect the multi-gpu inference when using accelerate device_map.Please make sure to update your driver to the latest version which resolves this.
Welcome to the GLM-4-9B CLI chat. Type your messages below.
Image Path:https://img1.baidu.com/it/u=1369931113,3388870256&fm=253&app=138&size=w931&n=0&f=JPEG&fmt=auto?sec=1703696400&t=f3028c7a1dca43a080aeb8239f09cc2f
Invalid image path. Continuing with text conversation.

You: 这是什么
thread '<unnamed>' panicked at 'index out of bounds: the len is 1 but the index is 1', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.8.1/src/dfa.rs:1415:45
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/data/rich/project/GLM-4/basic_demo/trans_cli_vision_demo.py", line 91, in <module>
    model_inputs = tokenizer.apply_chat_template(
  File "/root/.cache/huggingface/modules/transformers_modules/THUDM/glm-4v-9b/ade85af5ed77b437edf3cf4d941116026159a618/tokenization_chatglm.py", line 236, in apply_chat_template
    result = handle_single_conversation(conversation)
  File "/root/.cache/huggingface/modules/transformers_modules/THUDM/glm-4v-9b/ade85af5ed77b437edf3cf4d941116026159a618/tokenization_chatglm.py", line 216, in handle_single_conversation
    input = self.build_single_message(
  File "/root/.cache/huggingface/modules/transformers_modules/THUDM/glm-4v-9b/ade85af5ed77b437edf3cf4d941116026159a618/tokenization_chatglm.py", line 140, in build_single_message
    role_tokens = [self.convert_tokens_to_ids(f"<|{role}|>")] + self.tokenizer.encode(f"{metadata}\n",
  File "/root/anaconda3/lib/python3.9/site-packages/tiktoken/core.py", line 120, in encode
    return self._core_bpe.encode(text, allowed_special)
pyo3_runtime.PanicException: index out of bounds: the len is 1 but the index is 1

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

官方代码执行 python trans_cli_vision_demo.py

### Expected behavior / 期待表现

不知道是什么问题，是和环境有关吗？

**Comment by 641009368** [comment]
使用项目首页的快速推理也报错

Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
thread '<unnamed>' panicked at 'index out of bounds: the len is 1 but the index is 1', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.8.1/src/dfa.rs:1415:45
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/data/rich/project/GLM-4/basic_demo/trans_cli_vision_demo.py", line 11, in <module>
    inputs = tokenizer.apply_chat_template([{"role": "user", "image": image, "content": query}],
  File "/root/.cache/huggingface/modules/transformers_modules/THUDM/glm-4v-9b/ade85af5ed77b437edf3cf4d941116026159a618/tokenization_chatglm.py", line 236, in apply_chat_template
    result = handle_single_conversation(conversation)
  File "/root/.cache/huggingface/modules/transformers_modules/THUDM/glm-4v-9b/ade85af5ed77b437edf3cf4d941116026159a618/tokenization_chatglm.py", line 216, in handle_single_conversation
    input = self.build_single_message(
  File "/root/.cache/huggingface/modules/transformers_modules/THUDM/glm-4v-9b/ade85af5ed77b437edf3cf4d941116026159a618/tokenization_chatglm.py", line 140, in build_single_message
    role_tokens = [self.convert_tokens_to_ids(f"<|{role}|>")] + self.tokenizer.encode(f"{metadata}\n",
  File "/root/anaconda3/lib/python3.9/site-packages/tiktoken/core.py", line 120, in encode
    return self._core_bpe.encode(text, allowed_special)
pyo3_runtime.PanicException: index out of bounds: the len is 1 but the index is 1

**Comment by zRzRzRzRzRzRzR** [comment]
我怎么感觉是模型文件没有更新，或者你下载到了glm-9b这个base模型呢，所有demo是给chat模型用的

**Comment by FOLSc** [comment]
您好，请问“We've detected an older driver with an RTX 4000 series GPU. These drivers have issues with P2P. This can affect the multi-gpu inference when using accelerate device_map.Please make sure to update your driver to the latest version which resolves this.”这个问题您最终解决了吗？
