### ISSUE TITLE
Glm-4v-9b使用4bit加载报错

### ISSUE THREAD

**Issue by zhengyangyong** [THUDM/GLM-4#376]
### System Info / 系統信息

CUDA：12.4
OS：cuda:12.1.1-cudnn8-devel-rockylinux8

requirements.txt
```text
torch>=2.3.0
torchvision>=0.18.0
transformers==4.42.4
accelerate>=0.32.1
sentence_transformers>=3.0.1
bitsandbytes>=0.43.1
tiktoken>=0.7.0
fastapi
uvicorn
```

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [x] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

启动python代码：
```python
import torch
from PIL import Image
from transformers import AutoModelForCausalLM, AutoTokenizer
import uvicorn
from fastapi import FastAPI, Header, Body

model_path = '/data/model/Glm-4V-9B'

secret_key = '8cb3cffd0e5343ddb094ab547b559e84a7e409322c0a43a081f2a44bd05a07d1'
device = "cuda"
gen_kwargs = {"max_length": 500, "do_sample": True, "top_k": 1}

app = FastAPI()
model = AutoModelForCausalLM.from_pretrained(model_path, torch_dtype=torch.bfloat16, low_cpu_mem_usage=True,load_in_4bit=True,
                                             trust_remote_code=True).eval()
tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)

class Request(BaseModel):
    question: str
    image: str

@app.post("/recognise_image")
async def recognise_image(x_token: str = Header(None), request: Request = Body(None, content_type="application/json")):
    if x_token == None:
        return {"code": 401, "message": "请提供正确的Token"}
    if request == None:
        return {"code": 400, "message": "请求体不能为空"}
    if request.image == None:
        return {"code": 400, "message": "图片不能为空"}
    if request.question == None:
        return {"code": 400, "message": "问题不能为空"}

    image = Image.open(request.image).convert('RGB')
    inputs = tokenizer.apply_chat_template([{"role": "user", "image": image, "content": request.question}],
                                           add_generation_prompt=True, tokenize=True, return_tensors="pt",
                                           return_dict=True)
    inputs = inputs.to(device)
    with torch.no_grad():
        outputs = model.generate(**inputs, **gen_kwargs)
        outputs = outputs[:, inputs['input_ids'].shape[1]:]
    return {"code": 200, "data": tokenizer.decode(outputs[0])}


if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=6901)
```

报错信息：
```
The `load_in_4bit` and `load_in_8bit` arguments are deprecated and will be removed in the future versions. Please, pass a `BitsAndBytesConfig` object in `quantization_config` argument instead.
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 15/15 [00:05<00:00,  2.96it/s]
Traceback (most recent call last):
  File "/data/glm4v/main.py", line 17, in <module>
    tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)
  File "/usr/local/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 870, in from_pretrained
    tokenizer_class = get_class_from_dynamic_module(class_ref, pretrained_model_name_or_path, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/transformers/dynamic_module_utils.py", line 502, in get_class_from_dynamic_module
    final_module = get_cached_module_file(
  File "/usr/local/lib/python3.10/site-packages/transformers/dynamic_module_utils.py", line 327, in get_cached_module_file
    modules_needed = check_imports(resolved_module_file)
  File "/usr/local/lib/python3.10/site-packages/transformers/dynamic_module_utils.py", line 182, in check_imports
    raise ImportError(
ImportError: This modeling file requires the following packages that were not found in your environment: torchvision. Run `pip install torchvision`
```

实际上torchvision已经安装了：
```shell
pip3 list
```
输出:
```
Package                  Version
------------------------ ----------
accelerate               0.32.1
annotated-types          0.7.0
anyio                    4.4.0
bitsandbytes             0.43.1
certifi                  2024.7.4
charset-normalizer       3.3.2
click                    8.1.7
dnspython                2.6.1
email_validator          2.2.0
exceptiongroup           1.2.2
fastapi                  0.111.1
fastapi-cli              0.0.4
filelock                 3.15.4
fsspec                   2024.6.1
h11                      0.14.0
httpcore                 1.0.5
httptools                0.6.1
httpx                    0.27.0
huggingface-hub          0.24.0
idna                     3.7
Jinja2                   3.1.4
joblib                   1.4.2
markdown-it-py           3.0.0
MarkupSafe               2.1.5
mdurl                    0.1.2
mpmath                   1.3.0
networkx                 3.3
numpy                    1.26.4
nvidia-cublas-cu12       12.1.3.1
nvidia-cuda-cupti-cu12   12.1.105
nvidia-cuda-nvrtc-cu12   12.1.105
nvidia-cuda-runtime-cu12 12.1.105
nvidia-cudnn-cu12        8.9.2.26
nvidia-cufft-cu12        11.0.2.54
nvidia-curand-cu12       10.3.2.106
nvidia-cusolver-cu12     11.4.5.107
nvidia-cusparse-cu12     12.1.0.106
nvidia-nccl-cu12         2.20.5
nvidia-nvjitlink-cu12    12.5.82
nvidia-nvtx-cu12         12.1.105
packaging                24.1
pillow                   10.4.0
pip                      23.0.1
psutil                   6.0.0
pydantic                 2.8.2
pydantic_core            2.20.1
Pygments                 2.18.0
python-dotenv            1.0.1
python-multipart         0.0.9
PyYAML                   6.0.1
regex                    2024.5.15
requests                 2.32.3
rich                     13.7.1
safetensors              0.4.3
scikit-learn             1.5.1
scipy                    1.14.0
sentence-transformers    3.0.1
setuptools               65.5.0
shellingham              1.5.4
sniffio                  1.3.1
starlette                0.37.2
sympy                    1.13.1
threadpoolctl            3.5.0
tiktoken                 0.7.0
tokenizers               0.19.1
torch                    2.3.1
torchvision              0.18.1
tqdm                     4.66.4
transformers             4.42.4
triton                   2.3.1
typer                    0.12.3
typing_extensions        4.12.2
urllib3                  2.2.2
uvicorn                  0.30.3
uvloop                   0.19.0
watchfiles               0.22.0
websockets               12.0
```

### Expected behavior / 期待表现

能够按int4量化模式启动成功

**Comment by zRzRzRzRzRzRzR** [comment]
pip install torchvision 装这个，依赖没装全啊

**Comment by zhengyangyong** [comment]
系统依赖问题
