### ISSUE TITLE
报错：

### ISSUE THREAD

**Issue by jqtian123** [THUDM/GLM-4#382]
### System Info / 系統信息

Traceback (most recent call last):
  File "/opt/conda/envs/llamafactory/bin/llamafactory-cli", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/workspace/my_word/LLaMA-Factory-main/src/llamafactory/cli.py", line 111, in main
    run_exp()
  File "/workspace/my_word/LLaMA-Factory-main/src/llamafactory/train/tuner.py", line 50, in run_exp
    run_sft(model_args, data_args, training_args, finetuning_args, generating_args, callbacks)
  File "/workspace/my_word/LLaMA-Factory-main/src/llamafactory/train/sft/workflow.py", line 108, in run_sft
    predict_results = trainer.predict(dataset_module["eval_dataset"], metric_key_prefix="predict", **gen_kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/llamafactory/lib/python3.11/site-packages/transformers/trainer_seq2seq.py", line 244, in predict
    return super().predict(test_dataset, ignore_keys=ignore_keys, metric_key_prefix=metric_key_prefix)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/llamafactory/lib/python3.11/site-packages/transformers/trainer.py", line 3648, in predict
    output = eval_loop(
             ^^^^^^^^^^
  File "/opt/conda/envs/llamafactory/lib/python3.11/site-packages/transformers/trainer.py", line 3757, in evaluation_loop
    loss, logits, labels = self.prediction_step(model, inputs, prediction_loss_only, ignore_keys=ignore_keys)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/my_word/LLaMA-Factory-main/src/llamafactory/train/sft/trainer.py", line 99, in prediction_step
    loss, generated_tokens, _ = super().prediction_step(  # ignore the returned labels (may be truncated)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/llamafactory/lib/python3.11/site-packages/transformers/trainer_seq2seq.py", line 310, in prediction_step
    generated_tokens = self.model.generate(**generation_inputs, **gen_kwargs)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/llamafactory/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/llamafactory/lib/python3.11/site-packages/transformers/generation/utils.py", line 1758, in generate
    result = self._sample(
             ^^^^^^^^^^^^^
  File "/opt/conda/envs/llamafactory/lib/python3.11/site-packages/transformers/generation/utils.py", line 2449, in _sample
    model_kwargs = self._update_model_kwargs_for_generation(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/huggingface/modules/transformers_modules/glm-4-9b-chat/modeling_chatglm.py", line 930, in _update_model_kwargs_for_generation
    cache_name, cache = self._extract_past_from_model_output(
    ^^^^^^^^^^^^^^^^^
ValueError: too many values to unpack (expected 2)

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

合并模型之后做推理测试：llamafactory-cli train examples/train_lora/glm4_9b_lora_predict.yaml

### Expected behavior / 期待表现

求解决

**Comment by zhongfuxiao** [comment]
相同表现，已更新项目代码，安装requirement，已更新modelscope上的modeling_chatglm

**Comment by zRzRzRzRzRzRzR** [comment]
更新到最新的transformers，同时模型文件都需要更新
