### ISSUE TITLE
basic_demo中的两个vision代码出现visual文件的报错

### ISSUE THREAD

**Issue by wpNZC** [THUDM/GLM-4#383]
### System Info / 系統信息

系统环境/System Environment：

Ubuntu 20.04.5 LTS (GNU/Linux 5.15.0-76-generic x86_64) :
Tesla P40 + Driver Version: 535.183.01   CUDA Version: 12.2

版本号/Version：
Python：3.10.14, anaconda
Pytorch： torch-2.3.1+cu121-cp310-cp310-linux_x86_64.whl

basic_demo中的两个vision代码出现visual文件报错，考虑到因issue350的修改与报错建议，把4v模型文件中的visual.py73行改成output = self.dense(out.transpose(1, 2).reshape(B, L, -1))后得以正常运行。

报错如下：
Traceback (most recent call last):
  File "/root/anaconda3/envs/py310/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/root/anaconda3/envs/py310/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/root/anaconda3/envs/py310/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/anaconda3/envs/py310/lib/python3.10/site-packages/transformers/generation/utils.py", line 1914, in generate
    result = self._sample(
  File "/root/anaconda3/envs/py310/lib/python3.10/site-packages/transformers/generation/utils.py", line 2651, in _sample
    outputs = self(
  File "/root/anaconda3/envs/py310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/anaconda3/envs/py310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/anaconda3/envs/py310/lib/python3.10/site-packages/accelerate/hooks.py", line 169, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm4v-9b/modeling_chatglm.py", line 1179, in forward
    transformer_outputs = self.transformer(
  File "/root/anaconda3/envs/py310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/anaconda3/envs/py310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/anaconda3/envs/py310/lib/python3.10/site-packages/accelerate/hooks.py", line 169, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm4v-9b/modeling_chatglm.py", line 973, in forward
    images_features = self.vision(images)
  File "/root/anaconda3/envs/py310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/anaconda3/envs/py310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/anaconda3/envs/py310/lib/python3.10/site-packages/accelerate/hooks.py", line 169, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm4v-9b/visual.py", line 164, in forward
    x = self.transformer(x)
  File "/root/anaconda3/envs/py310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/anaconda3/envs/py310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/anaconda3/envs/py310/lib/python3.10/site-packages/accelerate/hooks.py", line 169, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm4v-9b/visual.py", line 126, in forward
    hidden_states = layer_module(hidden_states)
  File "/root/anaconda3/envs/py310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/anaconda3/envs/py310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/anaconda3/envs/py310/lib/python3.10/site-packages/accelerate/hooks.py", line 169, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm4v-9b/visual.py", line 109, in forward
    attention_output = self.input_layernorm(self.attention(attention_input))
  File "/root/anaconda3/envs/py310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/anaconda3/envs/py310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/anaconda3/envs/py310/lib/python3.10/site-packages/accelerate/hooks.py", line 169, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm4v-9b/visual.py", line 73, in forward
    output = self.dense(out.transpose(1, 2).view(B, L, -1))
RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.
Traceback (most recent call last):
  File "/data1/chat_model/ChatGLM4-9B/basic_demo/trans_cli_vision_demo.py", line 117, in <module>
    for new_token in streamer:
  File "/root/anaconda3/envs/py310/lib/python3.10/site-packages/transformers/generation/streamers.py", line 223, in __next__
    value = self.text_queue.get(timeout=self.timeout)
  File "/root/anaconda3/envs/py310/lib/python3.10/queue.py", line 179, in get
    raise Empty
_queue.Empty

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

仅修改模型文件路径及上述对visual.py line 73的修改

### Expected behavior / 期待表现

兼容

**Comment by zRzRzRzRzRzRzR** [comment]
卡太老了吧，要V100以上的卡

**Comment by wpNZC** [comment]
可是改回去就能用了， viev size is not comatible vith irut tensor's size and stride at least ae cimnenslon spans acros to cantiguous suhspaces. Use .reshape.. itead，报错也是直接叫这样改，其他卡没有影响吗

**Comment by zRzRzRzRzRzRzR** [comment]
output = self.dense(out.transpose(1, 2).reshape(B, L, -1))
直接改到模型文件夹下的visual.py

**Comment by wpNZC** [comment]
对，是这样
