### ISSUE TITLE
glm-4v-9b ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by zhongfuxiao** [THUDM/GLM-4#389]
### System Info / 系統信息

CUDA Version=12.2
Python=3.12.4
transformers=4.40.2
torch=2.3.1
NVIDIA L20 48G * 1

### Who can help? / 谁可以帮助到您？

@zRzRzRzRzRzRzR 

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

7月23日更新项目代码，下载modelscope上glm-4v-9b模型（搜到一些相同issue均不能解决，如更新transformer版本，更新模型中modeling_chatglm）
仅修改model_path和device_map
使用basic中trans_cli_vision_demo和composite_demo的多模态，均输出两三个字后出现如下报错：
这张Traceback (most recent call last):
  File "/data/anaconda3/envs/qallm/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/data/anaconda3/envs/qallm/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/data/anaconda3/envs/qallm/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/envs/qallm/lib/python3.12/site-packages/transformers/generation/utils.py", line 1622, in generate
    result = self._sample(
             ^^^^^^^^^^^^^
  File "/data/anaconda3/envs/qallm/lib/python3.12/site-packages/transformers/generation/utils.py", line 2841, in _sample
    model_kwargs = self._update_model_kwargs_for_generation(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/huggingface/modules/transformers_modules/glm-4v-9b/modeling_chatglm.py", line 1088, in _update_model_kwargs_for_generation
    cache_name, cache = self._extract_past_from_model_output(
    ^^^^^^^^^^^^^^^^^
ValueError: too many values to unpack (expected 2)

自行调试，self._extract_past_from_model_output会返回一个长度40的元组
烦请大佬抽空解答

### Expected behavior / 期待表现

模型返回正常

**Comment by zhongfuxiao** [comment]
已解决，更新transformers至4.42.4
