### ISSUE TITLE
在试图把GLM4导出为一个int4模型的时候出现了无法推理的情况。

### ISSUE THREAD

**Issue by zeiyu314** [THUDM/GLM-4#394]
### System Info / 系統信息

Windows11 23H2

Python 3.10.0rc2

库信息与requirement.txt一致。

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

1，使用以下代码导出：
`import torch,os
from transformers import AutoModelForCausalLM, AutoTokenizer

device = "cpu"

MODEL_PATH = os.environ.get('MODEL_PATH', 'THUDM/glm-4-9b-chat')

tokenizer = AutoTokenizer.from_pretrained(MODEL_PATH, trust_remote_code=True)

query = "你好"

inputs = tokenizer.apply_chat_template([{"role": "user", "content": query}],
                                       add_generation_prompt=True,
                                       tokenize=True,
                                       return_tensors="pt",
                                       return_dict=True
                                       )

inputs = inputs.to(device)
model = AutoModelForCausalLM.from_pretrained(
    MODEL_PATH,
    low_cpu_mem_usage=True,
    trust_remote_code=True,
    load_in_4bit=True
).eval()

model.save_pretrained("glm-4-9b-chat-int4")
tokenizer.save_pretrained("glm-4-9b-chat-int4")`

导出成功。
但是尝试使用官方示例trans_cli_demo.py推理的时候碰到了以下错误：
`GLM-4:Exception in thread 
Thread-2 (generate):
Traceback (most recent call last):
  File "c:\Users\Usr\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "c:\Users\Usr\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Users\Usr\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "c:\Users\Usr\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\generation\utils.py", line 1622, in generate
    result = self._sample(
  File "c:\Users\Usr\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\generation\utils.py", line 2841, in _sample
    model_kwargs = self._update_model_kwargs_for_generation(
  File "C:\Users\Usr\.cache\huggingface\modules\transformers_modules\THUDM\glm-4-9b-chat\c24133cef34ff7a7010f1e97c113effdead0966b\modeling_chatglm.py", line 930, in _update_model_kwargs_for_generation
    cache_name, cache = self._extract_past_from_model_output(
ValueError: too many values to unpack (expected 2)`

猜测可能是由于导出改变了张量形状，但是不知道如何修复。

### Expected behavior / 期待表现

与正常情况下一样的正确推理和基础功能。

**Comment by zRzRzRzRzRzRzR** [comment]
更新transformer到4.42以上
