### ISSUE TITLE
报错GenerationMixin._get_logits_warper() missing 1 required positional argument: 'device'

### ISSUE THREAD

**Issue by WenhaoYao** [THUDM/GLM-4#396]
### System Info / 系統信息

Docker：Xinference 0.31.2
Cuda:12.4
Transformers:v4.42.4

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

1.启动xinference:v0.13.2 
  xinference launch --model-engine Transformers --model-name glm4-chat-1m --size-in-billions 9 --model-format pytorch --  quantization none
2.xinference chat --model-uid glm4-chat-1m
3.2024-07-26 03:17:54,995 xoscar.api   1802 ERROR    Destroy generator a65ab9704afd11efa922fa163e35b767 due to an error encountered.
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/xoscar/api.py", line 417, in __xoscar_next__
    r = await asyncio.to_thread(_wrapper, gen)
  File "/opt/conda/lib/python3.10/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
  File "/opt/conda/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/conda/lib/python3.10/site-packages/xoscar/api.py", line 402, in _wrapper
    return next(_gen)
  File "/opt/conda/lib/python3.10/site-packages/xinference/core/model.py", line 300, in _to_json_generator
    for v in gen:
  File "/opt/conda/lib/python3.10/site-packages/xinference/model/llm/utils.py", line 544, in _to_chat_completion_chunks
    for i, chunk in enumerate(chunks):
  File "/opt/conda/lib/python3.10/site-packages/xinference/model/llm/pytorch/chatglm.py", line 172, in _stream_generator
    for chunk_text, _ in self._model.stream_chat(
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/root/.cache/huggingface/modules/transformers_modules/glm4-chat-1m-pytorch-9b/modeling_chatglm.py", line 1137, in stream_chat
    for outputs in self.stream_generate(**inputs, past_key_values=past_key_values,
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/root/.cache/huggingface/modules/transformers_modules/glm4-chat-1m-pytorch-9b/modeling_chatglm.py", line 1217, in stream_generate
    logits_warper = self._get_logits_warper(generation_config)
TypeError: GenerationMixin._get_logits_warper() missing 1 required positional argument: 'device'
2024-07-26 03:17:54,997 xinference.api.restful_api 1 ERROR    Chat completion stream got an error: [address=0.0.0.0:40387, pid=1802] GenerationMixin._get_logits_warper() missing 1 required positional argument: 'device'
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/xinference/api/restful_api.py", line 1476, in stream_results
    async for item in iterator:
  File "/opt/conda/lib/python3.10/site-packages/xoscar/api.py", line 340, in __anext__
    return await self._actor_ref.__xoscar_next__(self._uid)
  File "/opt/conda/lib/python3.10/site-packages/xoscar/backends/context.py", line 227, in send
    return self._process_result_message(result)
  File "/opt/conda/lib/python3.10/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/opt/conda/lib/python3.10/site-packages/xoscar/backends/pool.py", line 659, in send
    result = await self._run_coro(message.message_id, coro)
  File "/opt/conda/lib/python3.10/site-packages/xoscar/backends/pool.py", line 370, in _run_coro
    return await coro
  File "/opt/conda/lib/python3.10/site-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "/opt/conda/lib/python3.10/site-packages/xoscar/api.py", line 431, in __xoscar_next__
    raise e
  File "/opt/conda/lib/python3.10/site-packages/xoscar/api.py", line 417, in __xoscar_next__
    r = await asyncio.to_thread(_wrapper, gen)
  File "/opt/conda/lib/python3.10/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
  File "/opt/conda/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/conda/lib/python3.10/site-packages/xoscar/api.py", line 402, in _wrapper
    return next(_gen)
  File "/opt/conda/lib/python3.10/site-packages/xinference/core/model.py", line 300, in _to_json_generator
    for v in gen:
  File "/opt/conda/lib/python3.10/site-packages/xinference/model/llm/utils.py", line 544, in _to_chat_completion_chunks
    for i, chunk in enumerate(chunks):
  File "/opt/conda/lib/python3.10/site-packages/xinference/model/llm/pytorch/chatglm.py", line 172, in _stream_generator
    for chunk_text, _ in self._model.stream_chat(
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/root/.cache/huggingface/modules/transformers_modules/glm4-chat-1m-pytorch-9b/modeling_chatglm.py", line 1137, in stream_chat
    for outputs in self.stream_generate(**inputs, past_key_values=past_key_values,
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/root/.cache/huggingface/modules/transformers_modules/glm4-chat-1m-pytorch-9b/modeling_chatglm.py", line 1217, in stream_generate
    logits_warper = self._get_logits_warper(generation_config)
TypeError: [address=0.0.0.0:40387, pid=1802] GenerationMixin._get_logits_warper() missing 1 required positional argument: 'device'

### Expected behavior / 期待表现

能够正常运行

**Comment by zRzRzRzRzRzRzR** [comment]
这个要给xinfer提个issue了
