### ISSUE TITLE
请问出现 KeyError: 'sop'怎么解决

### ISSUE THREAD

**Issue by cangyizhou** [THUDM/GLM-4#399]
具体报错如下：
[rank0]: Traceback (most recent call last):
[rank0]:   File "/root/miniconda3/envs/glm4/lib/python3.10/site-packages/multiprocess/pool.py", line 125, in worker
[rank0]:     result = (True, func(*args, **kwds))
[rank0]:   File "/root/miniconda3/envs/glm4/lib/python3.10/site-packages/datasets/utils/py_utils.py", line 678, in _write_generator_to_queue
[rank0]:     for i, result in enumerate(func(**kwargs)):
[rank0]:   File "/root/miniconda3/envs/glm4/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 3552, in _map_single
[rank0]:     batch = apply_function_on_filtered_inputs(
[rank0]:   File "/root/miniconda3/envs/glm4/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 3421, in apply_function_on_filtered_inputs
[rank0]:     processed_inputs = function(*fn_args, *additional_args, **fn_kwargs)
[rank0]:   File "/root/autodl-tmp/DeepKE-main/example/llm/InstructKGC/src/datamodule/preprocess.py", line 57, in preprocess_supervised_dataset
[rank0]:     for turn_idx, (source_ids, target_ids) in enumerate(template.encode_multiturn(
[rank0]:   File "/root/autodl-tmp/DeepKE-main/example/llm/InstructKGC/src/datamodule/template.py", line 68, in encode_multiturn
[rank0]:     encoded_pairs = self._encode(tokenizer, system, history)
[rank0]:   File "/root/autodl-tmp/DeepKE-main/example/llm/InstructKGC/src/datamodule/template.py", line 121, in _encode
[rank0]:     prefix_ids = self._convert_inputs_to_ids(tokenizer, context=self.prefix, system=system)
[rank0]:   File "/root/autodl-tmp/DeepKE-main/example/llm/InstructKGC/src/datamodule/template.py", line 159, in _convert_inputs_to_ids
[rank0]:     token_ids = token_ids + [tokenizer.convert_tokens_to_ids(elem.get("token"))]
[rank0]:   File "/root/miniconda3/envs/glm4/lib/python3.10/site-packages/transformers/tokenization_utils.py", line 714, in convert_tokens_to_ids
[rank0]:     return self._convert_token_to_id_with_added_voc(tokens)
[rank0]:   File "/root/miniconda3/envs/glm4/lib/python3.10/site-packages/transformers/tokenization_utils.py", line 727, in _convert_token_to_id_with_added_voc
[rank0]:     return self._convert_token_to_id(token)
[rank0]:   File "/root/.cache/huggingface/modules/transformers_modules/glm-4-9b/tokenization_chatglm.py", line 95, in _convert_token_to_id
[rank0]:     return self.mergeable_ranks[token]
[rank0]: KeyError: 'sop'
我看有类似问题是transformers的原因，但是我的版本已经更新为4.43，仍然报错

**Comment by cangyizhou** [comment]
问题解决了
