### ISSUE TITLE
OCR效果

### ISSUE THREAD

**Issue by buptlihang** [THUDM/GLM-4#45]
感谢作者的开源！

我在使用过程中发现GLM4V-9B的OCR效果非常棒，想问一下会有相关的技术报告发布嘛？可以解答下大概用了多少OCR数据吗，是来自公开数据还是私有数据的呢

**Comment by Sleepychord** [comment]
使用了与https://github.com/THUDM/CogVLM2 相同的数据，大部分技术（除了模型结构更简化外）与团队之前的CogAgent 文章中类似 https://arxiv.org/abs/2312.08914 ，具体细节暂时没有详细介绍的计划。

**Comment by zRzRzRzRzRzRzR** [comment]
感谢解答！相关技术报告暂时没有提供，关于数据部分可以参考上面的链接

**Comment by kailiu9237** [comment]
我通过如下命令启动多模态大模型的时候遇到了运行时错误，请问有其它人碰到过吗？
`streamlit run src/main.py`

**错误日志1：**
Exception in thread Thread-18 (generate):
Traceback (most recent call last):
  File "/home/vipuser/anaconda3/envs/glm4.1/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/vipuser/anaconda3/envs/glm4.1/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/vipuser/anaconda3/envs/glm4.1/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/vipuser/anaconda3/envs/glm4.1/lib/python3.10/site-packages/transformers/generation/utils.py", line 1622, in generate
    result = self._sample(
  File "/home/vipuser/anaconda3/envs/glm4.1/lib/python3.10/site-packages/transformers/generation/utils.py", line 2791, in _sample
    outputs = self(
  File "/home/vipuser/anaconda3/envs/glm4.1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/vipuser/anaconda3/envs/glm4.1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/glm-4v-9b/modeling_chatglm.py", line 1017, in forward
    transformer_outputs = self.transformer(
  File "/home/vipuser/anaconda3/envs/glm4.1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/vipuser/anaconda3/envs/glm4.1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/glm-4v-9b/modeling_chatglm.py", line 855, in forward
    images_features = self.vision(images)
  File "/home/vipuser/anaconda3/envs/glm4.1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/vipuser/anaconda3/envs/glm4.1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/glm-4v-9b/visual.py", line 157, in forward
    x = self.transformer(x)
  File "/home/vipuser/anaconda3/envs/glm4.1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/vipuser/anaconda3/envs/glm4.1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/glm-4v-9b/visual.py", line 120, in forward
    hidden_states = layer_module(hidden_states)
  File "/home/vipuser/anaconda3/envs/glm4.1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/vipuser/anaconda3/envs/glm4.1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/glm-4v-9b/visual.py", line 105, in forward
    attention_output = self.input_layernorm(self.attention(attention_input))
  File "/home/vipuser/anaconda3/envs/glm4.1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/vipuser/anaconda3/envs/glm4.1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/glm-4v-9b/visual.py", line 69, in forward
    output = self.dense(out.transpose(1, 2).view(B, L, -1))
RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

**错误日志2：**
Traceback (most recent call last):
  File "/root/ZhipuAI/GLM-4/composite_demo/src/main.py", line 287, in main
    for response, chat_history in client.generate_stream(
  File "/root/ZhipuAI/GLM-4/composite_demo/src/clients/hf.py", line 57, in generate_stream
    for token_text in streamer:
  File "/home/vipuser/anaconda3/envs/glm4.1/lib/python3.10/site-packages/transformers/generation/streamers.py", line 223, in __next__
    value = self.text_queue.get(timeout=self.timeout)
  File "/home/vipuser/anaconda3/envs/glm4.1/lib/python3.10/queue.py", line 179, in get
    raise Empty
_queue.Empty


**环境信息**
系统OS：Ubuntu20
硬件及驱动：V100、CUDA11.8
Python版本及软件依赖：Python3.10、依赖参照官方给的requirement.txt安装

**Comment by buptlihang** [comment]
> 使用了与https://github.com/THUDM/CogVLM2 相同的数据，大部分技术（除了模型结构更简化外）与团队之前的CogAgent 文章中类似 https://arxiv.org/abs/2312.08914 ，具体细节暂时没有详细介绍的计划。

CogVLM2也没找到数据相关的介绍，所以数据这块有计划公开介绍嘛 :smiley:   @zRzRzRzRzRzRzR

**Comment by zRzRzRzRzRzRzR** [comment]
暂时没有，感谢您的支持，如果有相关的计划我们会在本github更新

**Comment by xbsdsongnan** [comment]
> 我通过如下命令启动多模态大模型的时候遇到了运行时错误，请问有其它人碰到过吗？ `streamlit run src/main.py`
> 
> **错误日志1：** Exception in thread Thread-18 (generate): Traceback (most recent call last): File "/home/vipuser/anaconda3/envs/glm4.1/lib/python3.10/threading.py", line 1016, in _bootstrap_inner self.run() File "/home/vipuser/anaconda3/envs/glm4.1/lib/python3.10/threading.py", line 953, in run self._target(*self._args, **self._kwargs) File "/home/vipuser/anaconda3/envs/glm4.1/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context return func(*args, **kwargs) File "/home/vipuser/anaconda3/envs/glm4.1/lib/python3.10/site-packages/transformers/generation/utils.py", line 1622, in generate result = self._sample( File "/home/vipuser/anaconda3/envs/glm4.1/lib/python3.10/site-packages/transformers/generation/utils.py", line 2791, in _sample outputs = self( File "/home/vipuser/anaconda3/envs/glm4.1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/home/vipuser/anaconda3/envs/glm4.1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl return forward_call(*args, **kwargs) File "/root/.cache/huggingface/modules/transformers_modules/glm-4v-9b/modeling_chatglm.py", line 1017, in forward transformer_outputs = self.transformer( File "/home/vipuser/anaconda3/envs/glm4.1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/home/vipuser/anaconda3/envs/glm4.1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl return forward_call(*args, **kwargs) File "/root/.cache/huggingface/modules/transformers_modules/glm-4v-9b/modeling_chatglm.py", line 855, in forward images_features = self.vision(images) File "/home/vipuser/anaconda3/envs/glm4.1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/home/vipuser/anaconda3/envs/glm4.1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl return forward_call(*args, **kwargs) File "/root/.cache/huggingface/modules/transformers_modules/glm-4v-9b/visual.py", line 157, in forward x = self.transformer(x) File "/home/vipuser/anaconda3/envs/glm4.1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/home/vipuser/anaconda3/envs/glm4.1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl return forward_call(*args, **kwargs) File "/root/.cache/huggingface/modules/transformers_modules/glm-4v-9b/visual.py", line 120, in forward hidden_states = layer_module(hidden_states) File "/home/vipuser/anaconda3/envs/glm4.1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/home/vipuser/anaconda3/envs/glm4.1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl return forward_call(*args, **kwargs) File "/root/.cache/huggingface/modules/transformers_modules/glm-4v-9b/visual.py", line 105, in forward attention_output = self.input_layernorm(self.attention(attention_input)) File "/home/vipuser/anaconda3/envs/glm4.1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/home/vipuser/anaconda3/envs/glm4.1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl return forward_call(*args, **kwargs) File "/root/.cache/huggingface/modules/transformers_modules/glm-4v-9b/visual.py", line 69, in forward output = self.dense(out.transpose(1, 2).view(B, L, -1)) RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.
> 
> **错误日志2：** Traceback (most recent call last): File "/root/ZhipuAI/GLM-4/composite_demo/src/main.py", line 287, in main for response, chat_history in client.generate_stream( File "/root/ZhipuAI/GLM-4/composite_demo/src/clients/hf.py", line 57, in generate_stream for token_text in streamer: File "/home/vipuser/anaconda3/envs/glm4.1/lib/python3.10/site-packages/transformers/generation/streamers.py", line 223, in **next** value = self.text_queue.get(timeout=self.timeout) File "/home/vipuser/anaconda3/envs/glm4.1/lib/python3.10/queue.py", line 179, in get raise Empty _queue.Empty
> 
> **环境信息** 系统OS：Ubuntu20 硬件及驱动：V100、CUDA11.8 Python版本及软件依赖：Python3.10、依赖参照官方给的requirement.txt安装

修改一下相应时间

**Comment by zRzRzRzRzRzRzR** [comment]
你这个应该是cuda和对应的依赖没装对，cuda11.8的依赖和测试的可能不一样
