### ISSUE TITLE
apply_chat_template 错误

### ISSUE THREAD

**Issue by tangfengdeng** [THUDM/GLM-4#551]
### System Info / 系統信息

使用requirments.txt构建

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

运行报错Traceback (most recent call last):
  File "/media/leege/ssd1/python_project/basic_demo/trans_batch_demo.py", line 75, in <module>
    new_batch_input = tokenizer.apply_chat_template(messages, add_generation_prompt=False, tokenize=False)
  File "/home/leege/anaconda3/envs/glm4/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 1786, in apply_chat_template
    chat_template = self.get_chat_template(chat_template, tools)
  File "/home/leege/anaconda3/envs/glm4/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2025, in get_chat_template
    raise ValueError(
ValueError: Cannot use apply_chat_template() because tokenizer.chat_template is not set and no template argument was passed! For information about writing templates and setting the tokenizer.chat_template attribute, please see the documentation at https://huggingface.co/docs/transformers/main/en/chat_templating

### Expected behavior / 期待表现

如何解决调用

**Comment by Shkklt** [comment]
你好，请问怎么解决的，可否分享一下？
