### ISSUE TITLE
使用composite_demo运行多模态模型出现错误RuntimeError: view size is not compatible with input tensor's size....

### ISSUE THREAD

**Issue by kailiu9237** [THUDM/GLM-4#59]
### System Info / 系統信息

- 系统OS：Ubuntu20
- 硬件型号：Nvidia V100
- CUDA版本：11.8
- Python版本：3.10
- 软件依赖：pip install -r requirements.txt

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

```
conda create -n glm4.1 python=3.10
conda activate glm4.1
cd ~/ZhipuAI/GLM-4/composite_demo
pip install -r requirements.txt
# 从modelscope下载glm-4v-9b到本地，如下命令启动本地模型
streamlit run  src/main.py
```

### Expected behavior / 期待表现

**多模态模式下，上传图片进行识别的时候出现如下错误日志，**

**错误日志1：**
Exception in thread Thread-18 (generate):
Traceback (most recent call last):
  File "/home/vipuser/anaconda3/envs/glm4.1/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/vipuser/anaconda3/envs/glm4.1/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/vipuser/anaconda3/envs/glm4.1/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/vipuser/anaconda3/envs/glm4.1/lib/python3.10/site-packages/transformers/generation/utils.py", line 1622, in generate
    result = self._sample(
  File "/home/vipuser/anaconda3/envs/glm4.1/lib/python3.10/site-packages/transformers/generation/utils.py", line 2791, in _sample
    outputs = self(
  File "/home/vipuser/anaconda3/envs/glm4.1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/vipuser/anaconda3/envs/glm4.1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/glm-4v-9b/modeling_chatglm.py", line 1017, in forward
    transformer_outputs = self.transformer(
  File "/home/vipuser/anaconda3/envs/glm4.1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/vipuser/anaconda3/envs/glm4.1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/glm-4v-9b/modeling_chatglm.py", line 855, in forward
    images_features = self.vision(images)
  File "/home/vipuser/anaconda3/envs/glm4.1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/vipuser/anaconda3/envs/glm4.1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/glm-4v-9b/visual.py", line 157, in forward
    x = self.transformer(x)
  File "/home/vipuser/anaconda3/envs/glm4.1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/vipuser/anaconda3/envs/glm4.1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/glm-4v-9b/visual.py", line 120, in forward
    hidden_states = layer_module(hidden_states)
  File "/home/vipuser/anaconda3/envs/glm4.1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/vipuser/anaconda3/envs/glm4.1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/glm-4v-9b/visual.py", line 105, in forward
    attention_output = self.input_layernorm(self.attention(attention_input))
  File "/home/vipuser/anaconda3/envs/glm4.1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/vipuser/anaconda3/envs/glm4.1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/glm-4v-9b/visual.py", line 69, in forward
    output = self.dense(out.transpose(1, 2).view(B, L, -1))
RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

**错误日志2：**
Traceback (most recent call last):
  File "/root/ZhipuAI/GLM-4/composite_demo/src/main.py", line 287, in main
    for response, chat_history in client.generate_stream(
  File "/root/ZhipuAI/GLM-4/composite_demo/src/clients/hf.py", line 57, in generate_stream
    for token_text in streamer:
  File "/home/vipuser/anaconda3/envs/glm4.1/lib/python3.10/site-packages/transformers/generation/streamers.py", line 223, in __next__
    value = self.text_queue.get(timeout=self.timeout)
  File "/home/vipuser/anaconda3/envs/glm4.1/lib/python3.10/queue.py", line 179, in get
    raise Empty
_queue.Empty

**Comment by czhko** [comment]
torch几 cu几

**Comment by OpenAndrus** [comment]
same issue here
![WX20240606-174859@2x](https://github.com/THUDM/GLM-4/assets/541488/2875588a-1a5e-4ed1-80e8-48402e66663c)

**Comment by hourshiqin** [comment]
在代码执行中（streamlit run  src/main.py），"错误日志2"我也遇到了，只有再次加载，但是多几次又出现。

**Comment by JeffRody** [comment]
同样问题

**Comment by JeffRody** [comment]
File "/root/.cache/huggingface/modules/transformers_modules/glm-4v-9b/visual.py", line 69, in forward
output = self.dense(out.transpose(1, 2).view(B, L, -1))
RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.修改文件里面用reshape

**Comment by JeffRody** [comment]
File "/root/.cache/huggingface/modules/transformers_modules/glm-4v-9b/visual.py", line 69, in forward
output = self.dense(out.transpose(1, 2).view(B, L, -1))
RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

**Comment by zRzRzRzRzRzRzR** [comment]
更新到最新的glm-4v的模型文件能解决吗 huggingface的

**Comment by Jamrainbow** [comment]
更新huggingface上visual.py和generation_config.json后解决报错
