### ISSUE TITLE
AttributeError: 'ChatGLM4Tokenizer' object has no attribute '_id'

### ISSUE THREAD

**Issue by yt7589** [THUDM/GLM-4#629]
### System Info / 系統信息

My environment:
cuda: 12.4
python: 3.12.7
torch: 2.5.0+cu124
transformer: 4.46.0
glm-4v-9b: the latest version (yesterday)

When I run basic_demo/trans_web_vision_demo.py it said: 
```
AttributeError: 'ChatGLM4Tokenizer' object has no attribute '_id'
```

How to solve this problem?

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

python trans_web_vision_demo.py

```
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████| 15/15 [00:11<00:00,  1.35it/s]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/media/psdz/dd70abba-ef8f-4187-ac20-157b242fbc5e/yantao/adev/GLM-4/apps/ira/core/ira_web.py", line 152, in <module>
    main(args=args)
  File "/media/psdz/dd70abba-ef8f-4187-ac20-157b242fbc5e/yantao/adev/GLM-4/apps/ira/core/ira_web.py", line 139, in main
    IraWeb.startup(params=params)
  File "/media/psdz/dd70abba-ef8f-4187-ac20-157b242fbc5e/yantao/adev/GLM-4/apps/ira/core/ira_web.py", line 69, in startup
    submit_button.click(IraWeb.chatbot,
  File "/home/psdz/diskb/software/anaconda3/envs/glm-4/lib/python3.12/site-packages/gradio/events.py", line 616, in event_trigger
    return Dependency(block, dep.get_config(), dep_index, fn)
                             ^^^^^^^^^^^^^^^^
  File "/home/psdz/diskb/software/anaconda3/envs/glm-4/lib/python3.12/site-packages/gradio/blocks.py", line 595, in get_config
    "inputs": [block._id for block in self.inputs],
               ^^^^^^^^^
AttributeError: 'ChatGLM4Tokenizer' object has no attribute '_id'
```

### Expected behavior / 期待表现

It should start the web page.

**Comment by sixsixcoder** [comment]
What version of gradio are you using?

**Comment by yt7589** [comment]
> What version of gradio are you using?

The version of gradio is 5.4.0

**Comment by sixsixcoder** [comment]
Please try to install gradio==4.44.1
