### ISSUE TITLE
运行trans_cli_demo.py ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by Udellliu** [THUDM/GLM-4#664]
### System Info / 系統信息

python3.10
cuda12.1
transformers4.40.2
运行程序报错，按博客的教程修改transformers版本为4.40.2后还是一样报错

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

python trans_cli_demo.py

### Expected behavior / 期待表现

You: you
GLM-4:Exception in thread Thread-2 (generate):
Traceback (most recent call last):
  File "/home/jdcw/anaconda3/envs/glm/lib/python3.12/threading.py", line 1075, in _bootstrap_inner

    self.run()
  File "/home/jdcw/anaconda3/envs/glm/lib/python3.12/threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jdcw/anaconda3/envs/glm/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jdcw/anaconda3/envs/glm/lib/python3.12/site-packages/transformers/generation/utils.py", line 1622, in generate
    result = self._sample(
             ^^^^^^^^^^^^^
  File "/home/jdcw/anaconda3/envs/glm/lib/python3.12/site-packages/transformers/generation/utils.py", line 2841, in _sample
    model_kwargs = self._update_model_kwargs_for_generation(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jdcw/.cache/huggingface/modules/transformers_modules/glm-4-9b-chat/modeling_chatglm.py", line 929, in _update_model_kwargs_for_generation
    cache_name, cache = self._extract_past_from_model_output(outputs)
    ^^^^^^^^^^^^^^^^^
ValueError: too many values to unpack (expected 2)

**Comment by sixsixcoder** [comment]
可以升级transformers到4.46.0以上

**Comment by Udellliu** [comment]
成功运行，感谢！



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年11月28日 15:37 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [THUDM/GLM-4] 运行trans_cli_demo.py ValueError: too many values to unpack (expected 2) (Issue #664) |

可以升级transformers到4.46.0以上
