### ISSUE TITLE
本地无法部署GLM-4，很多依赖包无法正常安装

### ISSUE THREAD

**Issue by diypyh** [THUDM/GLM-4#72]
### System Info / 系統信息

MacOS: Sonoma14.5 (23F79)
CPU: 2.4 GHz 八核Intel Core i9
内存：64 GB 2667 MHz DDR4

### Who can help? / 谁可以帮助到您？

使用Conda创建python=3.12.3环境，安装依赖包时，提示：torch最高版本是2.2.2（GLM-4版本：torch>=2.3.0），只能降到2.2.2，接着提示torchvision版本也要降到0.17.2（GLM-4版本：torchvision>=0.18.0）。当安装vllm>=0.4.3时，提示torch版本要>=2.3.0，没办法又降了vllm==0.4.1，结果直接安装失败了

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

`
Collecting vllm==0.4.1 (from -r requirements.txt (line 11))
  Using cached vllm-0.4.1.tar.gz (534 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      /private/var/folders/l5/m84lcs9s6rgfwz8f3zjbrsdc0000gn/T/pip-build-env-j2_ytls3/overlay/lib/python3.12/site-packages/torch/nn/modules/transformer.py:20: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:84.)
        device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),
      Traceback (most recent call last):
        File "/Users/panyh/miniconda3/envs/glm4/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/panyh/miniconda3/envs/glm4/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/panyh/miniconda3/envs/glm4/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/l5/m84lcs9s6rgfwz8f3zjbrsdc0000gn/T/pip-build-env-j2_ytls3/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/l5/m84lcs9s6rgfwz8f3zjbrsdc0000gn/T/pip-build-env-j2_ytls3/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/l5/m84lcs9s6rgfwz8f3zjbrsdc0000gn/T/pip-build-env-j2_ytls3/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 22, in <module>
      AssertionError: vLLM only supports Linux platform (including WSL).
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error
`

### Expected behavior / 期待表现

希望能出一个docker映像，或直接使用Ollama来启动

**Comment by zRzRzRzRzRzRzR** [comment]
清严格按照readme内的要求安装，windows不能装vLLM

**Comment by tangd** [comment]
> 清严格按照readme内的要求安装，windows不能装vLLM

他反馈的是macos的系统...
