### ISSUE TITLE
直接进行多卡推理的bug处理

### ISSUE THREAD

**Issue by cbigeyes** [THUDM/GLM-4#75]
### Feature request  / 功能建议

在使用transformers加载模型4v时，device map设置为多卡，推理时会报 RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cuda:2!

### Motivation / 动机

在使用transformers加载模型4v时，device map设置为多卡，推理时会报 RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cuda:2!

### Your contribution / 您的贡献

当修改modeling_chatglm.py中867行 为
![微信截图_20240606142619](https://github.com/THUDM/GLM-4/assets/26865840/790a7168-3633-42f8-9d07-20837d201cb5)
推理成功

**Comment by yangshao24** [comment]
我修改model_chatglm中上述位置后，还是显示上述错误，这是我的推理代码
import torch
from PIL import Image
from transformers import AutoModelForCausalLM, AutoTokenizer

device = "cuda"

tokenizer = AutoTokenizer.from_pretrained("/home/admin123/code/llm/ChatGLM/base/glm-4v-9b", trust_remote_code=True)

query = '描述这张图片'
image = Image.open("/home/admin123/code/llm/ChatGLM/GLM-4/test.png").convert('RGB')
inputs = tokenizer.apply_chat_template([{"role": "user", "image": image, "content": query}],
                                       add_generation_prompt=True, tokenize=True, return_tensors="pt",
                                       return_dict=True)  # chat mode

#inputs = inputs.to(device)
model = AutoModelForCausalLM.from_pretrained(
    "/home/admin123/code/llm/ChatGLM/base/glm-4v-9b",
    torch_dtype=torch.bfloat16,
    low_cpu_mem_usage=True,
    trust_remote_code=True,
    device_map="auto"
).eval()

gen_kwargs = {"max_length": 2500, "do_sample": True, "top_k": 1}
with torch.no_grad():
    outputs = model.generate(**inputs, **gen_kwargs)
    outputs = outputs[:, inputs['input_ids'].shape[1]:]
    print(tokenizer.decode(outputs[0]))
报错信息：
Loading checkpoint shards: 100%|█████████████████████████████████████████████████| 15/15 [00:11<00:00,  1.31it/s]
/home/admin123/miniforge3/envs/GLM/lib/python3.10/site-packages/transformers/generation/utils.py:1510: UserWarning: You are calling .generate() with the `input_ids` being on a device type different than your model's device. `input_ids` is on cpu, whereas the model is on cuda. You may experience unexpected behaviors or slower generation. Please make sure that you have put `input_ids` to the correct device by calling for example input_ids = input_ids.to('cuda') before running `.generate()`.
  warnings.warn(
Traceback (most recent call last):
  File "/home/admin123/code/llm/ChatGLM/GLM-4/9v_test.py", line 26, in <module>
    outputs = model.generate(**inputs, **gen_kwargs)
  File "/home/admin123/miniforge3/envs/GLM/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/admin123/miniforge3/envs/GLM/lib/python3.10/site-packages/transformers/generation/utils.py", line 1622, in generate
    result = self._sample(
  File "/home/admin123/miniforge3/envs/GLM/lib/python3.10/site-packages/transformers/generation/utils.py", line 2791, in _sample
    outputs = self(
  File "/home/admin123/miniforge3/envs/GLM/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/admin123/miniforge3/envs/GLM/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/admin123/miniforge3/envs/GLM/lib/python3.10/site-packages/accelerate/hooks.py", line 166, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/home/admin123/.cache/huggingface/modules/transformers_modules/glm-4v-9b/modeling_chatglm.py", line 1017, in forward
    transformer_outputs = self.transformer(
  File "/home/admin123/miniforge3/envs/GLM/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/admin123/miniforge3/envs/GLM/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/admin123/.cache/huggingface/modules/transformers_modules/glm-4v-9b/modeling_chatglm.py", line 855, in forward
    images_features = self.vision(images)
  File "/home/admin123/miniforge3/envs/GLM/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/admin123/miniforge3/envs/GLM/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/admin123/.cache/huggingface/modules/transformers_modules/glm-4v-9b/visual.py", line 157, in forward
    x = self.transformer(x)
  File "/home/admin123/miniforge3/envs/GLM/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/admin123/miniforge3/envs/GLM/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/admin123/.cache/huggingface/modules/transformers_modules/glm-4v-9b/visual.py", line 120, in forward
    hidden_states = layer_module(hidden_states)
  File "/home/admin123/miniforge3/envs/GLM/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/admin123/miniforge3/envs/GLM/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/admin123/.cache/huggingface/modules/transformers_modules/glm-4v-9b/visual.py", line 109, in forward
    output = mlp_input + mlp_output
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:3 and cuda:4!

**Comment by a624090359** [comment]
已经close的issue里有，需要更新一下文件

**Comment by zRzRzRzRzRzRzR** [comment]
4v没有吧，我们会检查一下

**Comment by zRzRzRzRzRzRzR** [comment]
已经更新
