### ISSUE TITLE
运行`basic_demo/trans_web_demo.py`的时候报错，无法找到模型路径

### ISSUE THREAD

**Issue by fjqz177** [THUDM/GLM-4#88]
### System Info / 系統信息

Win10
cuda 12.4
CPU: AMD 7945HX
RAM: 16GB
GPU: 4060 Laptop 8GB

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

按照[https://github.com/THUDM/GLM-4/blob/main/basic_demo/README.md](https://github.com/THUDM/GLM-4/blob/main/basic_demo/README.md)的教程

1. 手动安装`pytorch`
```
$ pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121
```

2. 补齐剩余依赖
```
$ pip install -r requirements.txt
```

3. 运行`basic_demo/trans_web_demo.py`的时候报`peft`未安装
```
$ pip install peft
```

4.运行
```
$ python trans_web_demo.py
```

出现如下报错
```
$ python trans_web_demo.py
Traceback (most recent call last):
  File "D:\biancheng\GLM-4\basic_demo\env\Lib\site-packages\transformers\utils\hub.py", line 398, in cached_file
    resolved_file = hf_hub_download(
                    ^^^^^^^^^^^^^^^^
  File "D:\biancheng\GLM-4\basic_demo\env\Lib\site-packages\huggingface_hub\utils\_validators.py", line 106, in _inner_fn
    validate_repo_id(arg_value)
  File "D:\biancheng\GLM-4\basic_demo\env\Lib\site-packages\huggingface_hub\utils\_validators.py", line 160, in validate_repo_id
    raise HFValidationError(
huggingface_hub.errors.HFValidationError: Repo id must use alphanumeric chars or '-', '_', '.', '--' and '..' are forbidden, '-' and '.' cannot start or end the name, max length is 96: 'D:\biancheng\GLM-4\basic_demo\THUDM\glm-4-9b-chat'.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\biancheng\GLM-4\basic_demo\trans_web_demo.py", line 58, in <module>
    model, tokenizer = load_model_and_tokenizer(MODEL_PATH, trust_remote_code=True)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\biancheng\GLM-4\basic_demo\trans_web_demo.py", line 48, in load_model_and_tokenizer
    model = AutoModelForCausalLM.from_pretrained(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\biancheng\GLM-4\basic_demo\env\Lib\site-packages\transformers\models\auto\auto_factory.py", line 484, in from_pretrained
    resolved_config_file = cached_file(
                           ^^^^^^^^^^^^
  File "D:\biancheng\GLM-4\basic_demo\env\Lib\site-packages\transformers\utils\hub.py", line 462, in cached_file
    raise EnvironmentError(
OSError: Incorrect path_or_model_id: 'D:\biancheng\GLM-4\basic_demo\THUDM\glm-4-9b-chat'. Please provide either the path to a local folder or the repo_id of a model on the Hub.
```

我的系统环境变量里面并没有`MODEL_PATH`之类的环境变量啊，我没记错以前的glm是可以直接运行就能自动下载模型的，按照这套教程在`kaggle`平台上也是同样的报错

尝试做出修改
```
MODEL_PATH = 'THUDM/glm-4-9b-chat'
TOKENIZER_PATH = os.environ.get("TOKENIZER_PATH", MODEL_PATH)
```
依旧是相同的报错

### Expected behavior / 期待表现

修复一下，kaggle上用不了就很难受

**Comment by SkyFlap** [comment]
要不要尝试一下模型路径修改为相对路径并使用"\\"替换"/"

**Comment by zRzRzRzRzRzRzR** [comment]
\ 改成 \\

**Comment by fjqz177** [comment]
以前的GLM部署web_demo的时候是可以自动下载模型文件的，请问这一代GLM-4是不是只能手动下载模型文件了呢？

**Comment by zRzRzRzRzRzRzR** [comment]
在代码中复用了之前的代码导致找不到文件，尝试手动下载到本地运行试试？我之后会改掉

**Comment by fjqz177** [comment]
我又试了一下
```
model = AutoModelForCausalLM.from_pretrained("THUDM/glm-4-9b-chat", trust_remote_code=True, device_map='auto')
tokenizer = AutoTokenizer.from_pretrained("THUDM/glm-4-9b-chat", trust_remote_code=True, use_fast=False)
```
把加载`model`那一行改成这样就能自动下载模型，实测在kaggle和colab还有本地都有效
